// LAPS Schema Enum Values
// Reference: docs/experimental/laps.schema_new4.json

export const FACILITY_TYPES = [
  'University Lab',
  'National Lab',
  'Government Lab',
  'Private Lab',
  'Other'
]

export const APPARATUS_TYPES = [
  'Uniaxial',
  'Triaxial (conventional)',
  'Biaxial',
  'True Triaxial',
  'Direct Shear',
  'Shear Box',
  'Rotary Shear Friction Apparatus',
  'Creep Cell',
  'Indentation Cell',
  'Piston Cylinder',
  'Multi Anvil',
  'D-DIA',
  'Rotational Drickamer Apparatus (RDA)',
  'Large Volume Torsion Apparatus (LVT)',
  '1 Atm Gas Mixing Furnace',
  'Vacuum Furnace',
  'Other Gas Medium Apparatus',
  'Other Solid Medium Apparatus',
  'Other Liquid Medium Apparatus',
  'Vickers Hardness Tester',
  'Nanoindenter',
  'Diamond Anvil Cell',
  'Brazilian Test',
  'Paterson Apparatus',
  'Heard Apparatus',
  'Griggs Apparatus',
  'Schmidt Hammer',
  'Split Hopkinson Pressure Bar',
  'Double Torsion apparatus',
  'Point Load',
  'Atomic Force Microscope',
  'Rheometer',
  'Permeameter',
  'Pycnometer',
  'Viscosimeter',
  'Laser Profilometer',
  'Light Interferometer',
  'Load Stamp',
  'Chevron Notch Test',
  'Paris-Edinburgh Rig',
  'NER Rig',
  'Sanchez Rig',
  'Micro-Deformation Cell',
  'Ancillary Equipment',
  'Commercial Apparatus',
  'Other Apparatus'
]

export const APPARATUS_FEATURES = [
  'Loading',
  'Unloading',
  'Heating',
  'Cooling',
  'High Temperature',
  'Ultra-High Temperature',
  'High Pressure',
  'Ultra-High Pressure',
  'HIP',
  'Synthesis',
  'Mineral Reactions',
  'Hydrothermal',
  'Elasticity',
  'Elastic Moduli',
  'Yield/Failure Strength',
  'Creep',
  'Friction',
  'Frictional Sliding',
  'Simple Shear',
  'Rotary Shear',
  'Pure Shear',
  'Indentation',
  'Hardness',
  'Dynamic Tests',
  'Hydraulic Fracturing',
  'Hydrothermal Fracturing',
  'Shockwave',
  'Reactive Flow',
  'Pore Fluid Control',
  'Permeability (Steady-State)',
  'Permeability (Transient)',
  'Drained',
  'Undrained',
  'Resistivity',
  'Electrical Capacitance',
  'Acoustic Velocity',
  'P-Wave Velocity',
  'S-Wave Velocity',
  'Tomography',
  'X-Ray',
  'Infrared',
  'Raman',
  'Visual'
]

export const PARAMETER_TYPES = [
  'Confining Pressure Pc',
  'Pore Pressure Pp',
  'Differential Stress σ1-σ3',
  'Maximum Stress σ1',
  'Intermediate Stress σ2',
  'Minimum Stress σ3',
  'Temperature T',
  'Displacement',
  'Strain Rate',
  'Force',
  'Torque',
  'RPM',
  'Frequency',
  'Amplitude',
  'Sample Diameter',
  'Sample Length',
  'Other'
]

export const UNIT_TYPES = [
  'degC',
  'degK',
  'sec',
  'min',
  'hour',
  'Volt',
  'mV',
  'Amperage',
  'mA',
  'Ohm',
  'Pa',
  'MPa',
  'GPa',
  'bar',
  'kbar',
  'N',
  'kN',
  'g',
  'mg',
  'μg',
  'm',
  'cm',
  'mm',
  'μm',
  'Hz',
  'kHz',
  'MHz',
  'Pa·s',
  'Darcy',
  'mDarcy',
  'm-1',
  'm2',
  'milistrain',
  'mm·sec-1',
  'N·sec-1',
  'sec-1',
  'kN·mm-1',
  '%',
  'count',
  'cc',
  'mm3'
]

export const UNIT_PREFIXES = [
  '1E+6',
  '1E+5',
  '1E+4',
  '1E+3',
  '1E+2',
  '1E+1',
  '-',
  '1E-1',
  '1E-2',
  '1E-3',
  '1E-4',
  '1E-5',
  '1E-6'
]

export const DOCUMENT_TYPES = [
  'Picture',
  'Diagram',
  'Manual',
  'Data',
  'Software',
  'Other'
]

export const DOCUMENT_FORMATS = [
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'csv',
  'txt',
  'jpg',
  'jpeg',
  'png',
  'gif',
  'tif',
  'tiff',
  'zip',
  'rar',
  'other'
]

// Sample-specific enums (from old app)
export const MATERIAL_TYPES = [
  'Glass',
  'Ice',
  'Ceramic',
  'Plastic',
  'Metal',
  'Soil',
  'Mineral',
  'Igneous Rock',
  'Sedimentary Rock',
  'Metamorphic Rock',
  'Epos Lithologies',
  'Standards',
  'Commodity'
]

export const MINERAL_TYPES = [
  'Other',
  'Actinolite',
  'Aegirine',
  'Albite',
  'Alkali - feldspar',
  'Amphibole',
  'Andesine',
  'Annite',
  'Anorthite',
  'Apatite',
  'Apophyllite',
  'Astrophyllite',
  'Augite',
  'Axinite',
  'Baryte',
  'Beryl',
  'Biopyribole',
  'Biopyrobole',
  'Biotite',
  'Brookite',
  'Calcic pyroxene',
  'Calcite',
  'Carbon',
  'Carbonates',
  'Cassiterite',
  'Celestine',
  'Celsian',
  'Chain silicates',
  'Chalcocite',
  'Chalcopyrite',
  'Corundum',
  'Cristobalite',
  'Cummingtonite',
  'Diamond',
  'Diaspore',
  'Diopside',
  'Dolomite',
  'Ekermannite',
  'Enstatite',
  'Epidote',
  'Epidote Group',
  'Feldspar',
  'Fe - Mg clinoamphibole',
  'Ferrosilite',
  'Fe - Ti oxide',
  'Galena',
  'Garnet',
  'Gedrite',
  'Gibbsite',
  'Glauconite',
  'Glaucophane',
  'Grunerite',
  'Gypsum',
  'Hedenbergite',
  'Hematite',
  'Hercynite',
  'Hornblende',
  'Humite',
  'Hydroxides',
  'Jadeite',
  'Kaersutite',
  'Kalsilite',
  'Kaolinite',
  'Katophorite',
  'K feldspar',
  'K - feldspar',
  'Kyanite',
  'Labradorite',
  'Larnite',
  'Lawsonite',
  'Lepidocrocite',
  'Lepidolite',
  'Leucite',
  'Limonite',
  'Magnesite',
  'Magnetite',
  'Margarite',
  'Melilite',
  'Merwinite',
  'Mica',
  'Microcline',
  'Monazite',
  'Montmorillonite',
  'Mullite',
  'Muscovite',
  'Native Elements',
  'Nepheline',
  'Oligoclase',
  'Olivine',
  'Omphacite',
  'Opaque',
  'Orthoamphibole',
  'Ortho - and Ring Silicates',
  'Orthoclase',
  'Orthopyroxene',
  'Oxides',
  'Paragonite',
  'Periclase',
  'Perovskite',
  'Perthite',
  'Phengite',
  'Phlogopite',
  'Phosphates',
  'Piemontite',
  'Plagioclase',
  'Prehnite',
  'Pumpellyite',
  'Pyrite',
  'Pyroxmangite',
  'Pyrrhotite',
  'Quartz',
  'Rankinite',
  'Rhodochrosite',
  'Rhodonite',
  'Richterite',
  'Riebeckite',
  'Rutile',
  'Sanidine',
  'Sapphirine',
  'Scapolite',
  'Sericite',
  'Spinel',
  'Spinel Group',
  'Spodumene',
  'Spurrite',
  'Staurolite',
  'Stilpnomelane',
  'Sulphates',
  'Sulphides',
  'Talc',
  'Tectosilicates',
  'Tilleyite',
  'Titanite',
  'Topaz',
  'Tourmaline',
  'Tremolite',
  'Tridymite',
  'Vermiculite',
  'Vesuvanite',
  'White Mica',
  'Wollastonite',
  'Wonesite',
  'Xenotime',
  'Zeolite',
  'Zircon',
  'Zoisite'
]

export const SAMPLE_PARAMETER_TYPES = [
  'Weight',
  'Connected Porosity',
  'Unconnected Porosity',
  'Total Porosity',
  'Density',
  'Permeability (Gas)',
  'Permeability (Water)',
  'Temperature',
  'Humidity',
  'Fluid Saturation',
  'Stress',
  'Other'
]

export const FRACTION_UNITS = [
  'Vol%',
  'Wt%',
  '%',
  'ppm',
  'ppb'
]

// Material state options
export const MATERIAL_STATES = [
  'Homogeneous',
  'Heterogeneous',
  'Powder/Gauge',
  'Discontinuous',
  'Continuous',
  'Composite'
]

// Soil type options (for Material Type = Soil)
export const SOIL_TYPES = [
  'Other',
  'Bentonite'
]

// Igneous rock options (for Material Type = Igneous Rock)
export const IGNEOUS_ROCK_TYPES = [
  'Other',
  'alkali feldspar granite',
  'andesite',
  'anorthosite',
  'aplite',
  'diabase',
  'diorite',
  'granite',
  'harzburgite',
  'lapilli tuff',
  'norite',
  'pegmatite',
  'peridotite',
  'quartz monzonite',
  'rhyolite',
  'syenite',
  'tonalite',
  'trachyandesite',
  'tuff breccia'
]

// Sedimentary rock options (for Material Type = Sedimentary Rock)
export const SEDIMENTARY_ROCK_TYPES = [
  'Other',
  'breccia',
  'chert',
  'conglomerate',
  'dolostone',
  'coal',
  'organic',
  'phosphatic',
  'siltstone',
  'volcaniclastic',
  'sandstone',
  'limestone',
  'shale'
]

// Metamorphic rock options (for Material Type = Metamorphic Rock)
export const METAMORPHIC_ROCK_TYPES = [
  'Other',
  'slate',
  'amphibolite',
  'blackwall',
  'blueschist',
  'garnetite',
  'glaucophanite',
  'granulite',
  'greenstone',
  'hornfels',
  'metaarkose',
  'metabasite',
  'metacarbonate',
  'metagranite',
  'metagraywacke',
  'metaigneous',
  'meta-iron formation',
  'meta-ultramafic',
  'orthogneiss',
  'paragneiss',
  'phyllite',
  'phyllonite',
  'pyroxenite',
  'quartzite',
  'schist',
  'serpentinite',
  'skarn'
]

// Epos lithology options (for Material Type = Epos Lithologies)
export const EPOS_LITHOLOGY_TYPES = [
  'Other',
  'acidic_igneous_material',
  'acidic_igneous_rock',
  'alkali_feldspar_granite',
  'alkali_feldspar_rhyolite',
  'alkali_feldspar_syenite',
  'alkali_feldspar_syenitic_rock',
  'alkali_feldspar_trachyte',
  'alkali_feldspar_trachytic_rock',
  'alkali - olivine_basalt',
  'amphibolite',
  'andesite',
  'anorthosite',
  'anorthositic_rock',
  'anthracite_coal',
  'anthropogenic_material',
  'anthropogenic_unconsolidated_material',
  'aphanite',
  'aplite',
  'arenite',
  'ash_and_lapilli',
  'ash_breccia_bomb_or_block_tephra',
  'ash_tuff_lapillistone_and_lapilli_tuff',
  'basalt',
  'basanite',
  'basanitic_foidite',
  'basic_igneous_material',
  'basic_igneous_rock',
  'bauxite',
  'biogenic_sediment',
  'biogenic_silica_sedimentary_rock',
  'bituminous_coal',
  'boninite',
  'boulder_gravel_size_sediment',
  'boundstone',
  'breccia',
  'breccia_gouge_series',
  'calcareous_carbonate_sediment',
  'calcareous_carbonate_sedimentary_material',
  'calcareous_carbonate_sedimentary_rock',
  'carbonate_mud',
  'carbonate_mudstone',
  'carbonate_ooze',
  'carbonate_rich_mud',
  'carbonate_rich_mudstone',
  'carbonate_sediment',
  'carbonate_sedimentary_material',
  'carbonate_sedimentary_rock',
  'carbonate_wackestone',
  'carbonatite',
  'cataclasite_series',
  'chalk',
  'chemical_sedimentary_material',
  'chlorite_actinolite_epidote_metamorphic_rock',
  'clastic_conglomerate',
  'clastic_mudstone',
  'clastic_sandstone',
  'clastic_sediment',
  'clastic_sedimentary_material',
  'clastic_sedimentary_rock',
  'clay',
  'claystone',
  'coal',
  'cobble_gravel_size_sediment',
  'composite_genesis_material',
  'composite_genesis_rock',
  'compound_material',
  'crystalline_carbonate',
  'dacite',
  'diamictite',
  'diamicton',
  'diorite',
  'dioritic_rock',
  'dioritoid',
  'doleritic_rock',
  'dolomitic_or_magnesian_sedimentary_material',
  'dolomitic_or_magnesian_sedimentary_rock',
  'dolomitic_sediment',
  'dolostone',
  'duricrust',
  'eclogite',
  'evaporite',
  'exotic_alkaline_rock',
  'exotic_composition_igneous_rock',
  'exotic_evaporite',
  'fault_related_material',
  'fine_grained_igneous_rock',
  'foid_bearing_alkali_feldspar_syenite',
  'foid_bearing_alkali_feldspar_trachyte',
  'foid_bearing_anorthosite',
  'foid_bearing_diorite',
  'foid_bearing_gabbro',
  'foid_bearing_latite',
  'foid_bearing_monzodiorite',
  'foid_bearing_monzogabbro',
  'foid_bearing_monzonite',
  'foid_bearing_syenite',
  'foid_bearing_trachyte',
  'foid_diorite',
  'foid_dioritoid',
  'foid_gabbro',
  'foid_gabbroid',
  'foid_monzodiorite',
  'foid_monzogabbro',
  'foid_monzosyenite',
  'foid_syenite',
  'foid_syenitoid',
  'foidite',
  'foiditoid',
  'foidolite',
  'foliated_metamorphic_rock',
  'fragmental_igneous_material',
  'fragmental_igneous_rock',
  'framestone',
  'gabbro',
  'gabbroic_rock',
  'gabbroid',
  'generic_conglomerate',
  'generic_mudstone',
  'generic_sandstone',
  'glass_rich_igneous_rock',
  'glassy_igneous_rock',
  'glaucophane_lawsonite_epidote_metamorphic_rock',
  'gneiss',
  'grainstone',
  'granite',
  'granitoid',
  'granodiorite',
  'granofels',
  'granulite',
  'gravel',
  'gravel_size_sediment',
  'high_magnesium_fine_grained_igneous_rocks',
  'hornblendite',
  'hornfels',
  'hybrid_sediment',
  'hybrid_sedimentary_rock',
  'igneous_material',
  'igneous_rock',
  'impact_generated_material',
  'impure_calcareous_carbonate_sediment',
  'impure_carbonate_sediment',
  'impure_carbonate_sedimentary_rock',
  'impure_dolomitic_sediment',
  'impure_dolostone',
  'impure_limestone',
  'intermediate_composition_igneous_material',
  'intermediate_composition_igneous_rock',
  'iron_rich_sediment',
  'iron_rich_sedimentary_material',
  'iron_rich_sedimentary_rock',
  'kalsilitic_and_melilitic_rock',
  'komatiitic_rock',
  'latite',
  'latitic_rock',
  'lignite',
  'limestone',
  'marble',
  'material_formed_in_surficial_environment',
  'metamorphic_rock',
  'metasomatic_rock',
  'mica_schist',
  'migmatite',
  'monzodiorite',
  'monzodioritic_rock',
  'monzogabbro',
  'monzogabbroic_rock',
  'monzogranite',
  'monzonite',
  'monzonitic_rock',
  'mud',
  'mud_size_sediment',
  'mylonitic_rock',
  'natural_unconsolidated_material',
  'non_clastic_siliceous_sediment',
  'non_clastic_siliceous_sedimentary_material',
  'non_clastic_siliceous_sedimentary_rock',
  'ooze',
  'organic_bearing_mudstone',
  'organic_rich_sediment',
  'organic_rich_sedimentary_material',
  'organic_rich_sedimentary_rock',
  'orthogneiss',
  'packstone',
  'paragneiss',
  'peat',
  'pegmatite',
  'peridotite',
  'phaneritic_igneous_rock',
  'phonolilte',
  'phonolitic_basanite',
  'phonolitic_foidite',
  'phonolitic_tephrite',
  'phonolitoid',
  'phosphate_rich_sediment',
  'phosphate_rich_sedimentary_material',
  'phosphorite',
  'phyllite',
  'phyllonite',
  'porphyry',
  'pure_calcareous_carbonate_sediment',
  'pure_carbonate_mudstone',
  'pure_carbonate_sediment',
  'pure_carbonate_sedimentary_rock',
  'pure_dolomitic_sediment',
  'pyroclastic_material',
  'pyroclastic_rock',
  'pyroxenite',
  'quartz_alkali_feldspar_syenite',
  'quartz_alkali_feldspar_trachyte',
  'quartz_anorthosite',
  'quartz_diorite',
  'quartz_gabbro',
  'quartz_latite',
  'quartz_monzodiorite',
  'quartz_monzogabbro',
  'quartz_monzonite',
  'quartz_rich_igneous_rock',
  'quartz_syenite',
  'quartz_trachyte',
  'quartzite',
  'residual_material',
  'rhyolite',
  'rhyolitoid',
  'rock',
  'rock_gypsum_or_anhydrite',
  'rock_salt',
  'sand',
  'sand_size_sediment',
  'sapropel',
  'schist',
  'sediment',
  'sedimentary_material',
  'sedimentary_rock',
  'serpentinite',
  'shale',
  'silicate_mud',
  'silicate_mudstone',
  'siliceous_ooze',
  'silt',
  'siltstone',
  'skarn',
  'slate',
  'spilite',
  'syenite',
  'syenitic_rock',
  'syenitoid',
  'syenogranite',
  'tephra',
  'tephrite',
  'tephritic_foidite',
  'tephritic_phonolite',
  'tephritoid',
  'tholeiitic_basalt',
  'tonalite',
  'trachyte',
  'trachytic_rock',
  'trachytoid',
  'travertine',
  'tuff_breccia_agglomerate_or_pyroclastic_breccia',
  'tuffite',
  'ultrabasic_igneous_rock',
  'ultramafic_igneous_rock',
  'unconsolidated_material',
  'wacke'
]

// Lab standards options (for Material Type = Standards)
export const LAB_STANDARDS = [
  'Other',
  'Austin Chalk',
  'Berea Sandstone',
  'Carrara Marble',
  'Indiana Limestone',
  'Frederick Maryland Diabase',
  'Heavitree Quartzite',
  'Solnhofen Limestone',
  'Simpson Quartzite',
  'Black Hills Quartzite',
  'Sioux Quartzite',
  'Cheshire Quartzite',
  'Arkansas Novaculite',
  'Westerley Granite'
]

// Commodity options (for Material Type = Commodity)
export const COMMODITY_TYPES = [
  'Other',
  'agate',
  'aggregate',
  'alumina',
  'aluminium',
  'aluminosilicate',
  'alunite',
  'amazonite',
  'amber',
  'amethyst',
  'andalusite',
  'anhydrite',
  'anthophyllite',
  'anthracite',
  'antimony',
  'apatite',
  'apatite - gemstone',
  'aquamarine',
  'arsenic',
  'asbestos',
  'asbestos - amphibole',
  'asbestos - serpentine',
  'asphalt',
  'barium',
  'baryte',
  'basalt',
  'base - metal',
  'bauxite',
  'bentonite',
  'beryl',
  'beryllium',
  'bismuth',
  'black - coal',
  'borate',
  'boron',
  'brick - clay',
  'bromine',
  'brown - coal',
  'cadmium',
  'calcite',
  'carbonaceous - material',
  'carnallite',
  'carnelian',
  'cassiterite - gemstone',
  'cerium',
  'cesium',
  'chalcedony',
  'chemical - compound - product',
  'chemical - oxide - product',
  'chert',
  'chlorite',
  'chrome',
  'chromite',
  'chromium',
  'chrysoberyl',
  'chrysoprase',
  'chrysotile',
  'citrine',
  'clay',
  'coal',
  'coal - bed - methane',
  'cobalt',
  'copper',
  'corundum',
  'corundum - gemstone',
  'crocidolite',
  'crushed - rock',
  'cryolite',
  'diamond',
  'diamond - gemstone',
  'diatomite',
  'dimension - stone',
  'diopside - enstatite',
  'dioptase',
  'direct - shipping - ore',
  'direct - use - commodity',
  'dumortierite',
  'dysprosium',
  'emerald',
  'epsomite',
  'erbium',
  'euclase',
  'europium',
  'evaporite',
  'feldspar',
  'feldspar - gemstone',
  'ferrous - metal',
  'fluorine',
  'fluorite',
  'foundry - sand',
  'frac - sand',
  'fullers - earth',
  'gadolinium',
  'gallium',
  'garnet',
  'garnet - gemstone',
  'gaseous - hydrocarbons',
  'gas - hydrate',
  'gemstones',
  'germanium',
  'glauconite',
  'gold',
  'granite',
  'graphite',
  'greenstone',
  'gypsum',
  'hafnium',
  'halloysite',
  'heavy - rare - earth - oxide',
  'heliodor',
  'hematite',
  'hematite - gemstone',
  'hematite - ore',
  'holmium',
  'hree',
  'ilmenite',
  'indium',
  'industrial - material',
  'industrial - mineral',
  'industrial - rock',
  'iodine',
  'iolite',
  'iridium',
  'iron',
  'iron - ore',
  'iron - oxide',
  'jade',
  'jarosite',
  'kaolin',
  'kornerupine',
  'kyanite',
  'kyanite - gemstone',
  'lanthanum',
  'laterite',
  'lazulite',
  'lead',
  'leucoxene',
  'light - rare - earth - oxide',
  'lime',
  'limestone',
  'liquid - hydrocarbons',
  'lithium',
  'lithium - oxide',
  'lree',
  'lutetium',
  'magnesia',
  'magnesite',
  'magnesium',
  'magnetite',
  'magnetite - ore',
  'malachite',
  'manganese',
  'manganese - ore',
  'marble',
  'mercury',
  'metal',
  'metalloid',
  'mica',
  'miscellaneous - dimension - stones',
  'molybdenite',
  'molybdenum',
  'monazite',
  'moonstone',
  'morganite',
  'moss - agate',
  'natural - secondary - aggregate',
  'neodymium',
  'nepheline - syenite',
  'nickel',
  'niobium',
  'niobium - pentoxide',
  'nitrate',
  'non - metal',
  'obsidian',
  'ochre',
  'oil',
  'oil - shale',
  'olivine',
  'olivine - gemstone',
  'onyx',
  'opal',
  'organic - material',
  'osmium',
  'palladium',
  'palygorskite',
  'peat',
  'perlite',
  'phenakite',
  'phosphate - rock',
  'phosphorous',
  'phosphorous - pentoxide',
  'platinum',
  'platinum - group',
  'potash',
  'potassium',
  'pozzolan',
  'praseodymium',
  'precious - metal',
  'prehnite',
  'primary - aggregate',
  'produced - commodity',
  'promethium',
  'pumice',
  'pyrite',
  'pyrophyllite',
  'quartz',
  'quartz - gemstone',
  'radium',
  'rare - earth - element',
  'rare - earth - oxide',
  'recycled - aggregate',
  'reservoir - gas',
  'rhenium',
  'rhodium',
  'rhodonite',
  'riprap',
  'rose - quartz',
  'rubidium',
  'ruby',
  'ruthenium',
  'rutile',
  'salt',
  'samarium',
  'sand',
  'sand - and - gravel',
  'sandstone',
  'saponite',
  'sapphire',
  'sapphirine',
  'scandium',
  'scapolite',
  'selenium',
  'sepiolite',
  'sericite',
  'serpentine',
  'shell - grit',
  'silica',
  'silica - gemstone',
  'silicon',
  'sillimanite',
  'silver',
  'sinhalite',
  'slate',
  'smokey - quartz',
  'soda - ash',
  'sodalite',
  'spectrolite',
  'spinel',
  'spinel - gemstone',
  'spodumene',
  'spongolite',
  'staurolite',
  'strontianite',
  'strontium',
  'sulphur',
  'sylvite',
  'talc',
  'tantalum',
  'tantalum - pentoxide',
  'tanzanite',
  'tar - sand',
  'tellurium',
  'terbium',
  'thallium',
  'thenardite',
  'thorium',
  'thulium',
  'tin',
  'titanium',
  'topaz',
  'tourmaline',
  'tremolite - actinolite',
  'tsavorite',
  'tungsten',
  'turquoise',
  'uranium',
  'uranium - oxide',
  'vanadium',
  'vanadium - pentoxide',
  'variscite',
  'vermiculite',
  'vesuvianite',
  'white - firing - clay',
  'wollastonite',
  'xenotime - gemstone',
  'ytterbium',
  'yttrium',
  'yttrium - oxide',
  'zeolite',
  'zinc',
  'zircon',
  'zircon - gemstone',
  'zirconia',
  'zirconium'
]

// Material types that use text input for name (instead of dropdown)
export const TEXT_INPUT_MATERIAL_TYPES = [
  'Glass',
  'Ice',
  'Ceramic',
  'Plastic',
  'Metal'
]

// Mapping of material type to label for the name field
export const MATERIAL_NAME_LABELS = {
  'Glass': 'Name',
  'Ice': 'Name',
  'Ceramic': 'Name',
  'Plastic': 'Name',
  'Metal': 'Name',
  'Soil': 'Soil Type',
  'Mineral': 'Mineral Name',
  'Igneous Rock': 'Igneous Rock',
  'Sedimentary Rock': 'Sedimentary Rock',
  'Metamorphic Rock': 'Metamorphic Rock',
  'Epos Lithologies': 'Epos Lithology',
  'Standards': 'Lab Standard',
  'Commodity': 'Commodity Name'
}

// Mapping of material type to dropdown options
export const MATERIAL_NAME_OPTIONS = {
  'Soil': SOIL_TYPES,
  'Mineral': null, // Uses MINERAL_TYPES (already defined)
  'Igneous Rock': IGNEOUS_ROCK_TYPES,
  'Sedimentary Rock': SEDIMENTARY_ROCK_TYPES,
  'Metamorphic Rock': METAMORPHIC_ROCK_TYPES,
  'Epos Lithologies': EPOS_LITHOLOGY_TYPES,
  'Standards': LAB_STANDARDS,
  'Commodity': COMMODITY_TYPES
}
