// LAPS Schema Enum Values
// Reference: docs/experimental/laps.schema_new4.json

export const FACILITY_TYPES = [
  'University Lab',
  'National Lab',
  'Government Lab',
  'Private Lab',
  'Other'
]

export const APPARATUS_TYPES = [
  'Uniaxial',
  'Triaxial (conventional)',
  'Biaxial',
  'True Triaxial',
  'Direct Shear',
  'Shear Box',
  'Rotary Shear Friction Apparatus',
  'Creep Cell',
  'Indentation Cell',
  'Piston Cylinder',
  'Multi Anvil',
  'D-DIA',
  'Rotational Drickamer Apparatus (RDA)',
  'Large Volume Torsion Apparatus (LVT)',
  '1 Atm Gas Mixing Furnace',
  'Vacuum Furnace',
  'Other Gas Medium Apparatus',
  'Other Solid Medium Apparatus',
  'Other Liquid Medium Apparatus',
  'Vickers Hardness Tester',
  'Nanoindenter',
  'Diamond Anvil Cell',
  'Brazilian Test',
  'Paterson Apparatus',
  'Heard Apparatus',
  'Griggs Apparatus',
  'Schmidt Hammer',
  'Split Hopkinson Pressure Bar',
  'Double Torsion apparatus',
  'Point Load',
  'Atomic Force Microscope',
  'Rheometer',
  'Permeameter',
  'Pycnometer',
  'Viscosimeter',
  'Laser Profilometer',
  'Light Interferometer',
  'Load Stamp',
  'Chevron Notch Test',
  'Paris-Edinburgh Rig',
  'NER Rig',
  'Sanchez Rig',
  'Micro-Deformation Cell',
  'Ancillary Equipment',
  'Commercial Apparatus',
  'Other Apparatus'
]

export const APPARATUS_FEATURES = [
  'Loading',
  'Unloading',
  'Heating',
  'Cooling',
  'High Temperature',
  'Ultra-High Temperature',
  'High Pressure',
  'Ultra-High Pressure',
  'HIP',
  'Synthesis',
  'Mineral Reactions',
  'Hydrothermal',
  'Elasticity',
  'Elastic Moduli',
  'Yield/Failure Strength',
  'Creep',
  'Friction',
  'Frictional Sliding',
  'Simple Shear',
  'Rotary Shear',
  'Pure Shear',
  'Indentation',
  'Hardness',
  'Dynamic Tests',
  'Hydraulic Fracturing',
  'Hydrothermal Fracturing',
  'Shockwave',
  'Reactive Flow',
  'Pore Fluid Control',
  'Permeability (Steady-State)',
  'Permeability (Transient)',
  'Drained',
  'Undrained',
  'Resistivity',
  'Electrical Capacitance',
  'Acoustic Velocity',
  'P-Wave Velocity',
  'S-Wave Velocity',
  'Tomography',
  'X-Ray',
  'Infrared',
  'Raman',
  'Visual'
]

export const PARAMETER_TYPES = [
  'Confining Pressure Pc',
  'Pore Pressure Pp',
  'Differential Stress σ1-σ3',
  'Maximum Stress σ1',
  'Intermediate Stress σ2',
  'Minimum Stress σ3',
  'Temperature T',
  'Displacement',
  'Strain Rate',
  'Force',
  'Torque',
  'RPM',
  'Frequency',
  'Amplitude',
  'Sample Diameter',
  'Sample Length',
  'Other'
]

export const UNIT_TYPES = [
  'degC',
  'degK',
  'sec',
  'min',
  'hour',
  'Volt',
  'mV',
  'Amperage',
  'mA',
  'Ohm',
  'Pa',
  'MPa',
  'GPa',
  'bar',
  'kbar',
  'N',
  'kN',
  'g',
  'mg',
  'μg',
  'm',
  'cm',
  'mm',
  'μm',
  'Hz',
  'kHz',
  'MHz',
  'Pa·s',
  'Darcy',
  'mDarcy',
  'm-1',
  'm2',
  'milistrain',
  'mm·sec-1',
  'N·sec-1',
  'sec-1',
  'kN·mm-1',
  '%',
  'count',
  'cc',
  'mm3'
]

export const UNIT_PREFIXES = [
  '1E+6',
  '1E+5',
  '1E+4',
  '1E+3',
  '1E+2',
  '1E+1',
  '-',
  '1E-1',
  '1E-2',
  '1E-3',
  '1E-4',
  '1E-5',
  '1E-6'
]

export const DOCUMENT_TYPES = [
  'Picture',
  'Diagram',
  'Manual',
  'Data',
  'Software',
  'Other'
]

export const DOCUMENT_FORMATS = [
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'csv',
  'txt',
  'jpg',
  'jpeg',
  'png',
  'gif',
  'tif',
  'tiff',
  'zip',
  'rar',
  'other'
]

// Sample-specific enums (from old app)
export const MATERIAL_TYPES = [
  'Glass',
  'Ice',
  'Ceramic',
  'Plastic',
  'Metal',
  'Soil',
  'Mineral',
  'Igneous Rock',
  'Sedimentary Rock',
  'Metamorphic Rock',
  'Epos Lithologies',
  'Standards',
  'Commodity'
]

export const MINERAL_TYPES = [
  'Other',
  'Actinolite',
  'Aegirine',
  'Albite',
  'Alkali - feldspar',
  'Amphibole',
  'Andesine',
  'Annite',
  'Anorthite',
  'Apatite',
  'Apophyllite',
  'Astrophyllite',
  'Augite',
  'Axinite',
  'Baryte',
  'Beryl',
  'Biopyribole',
  'Biopyrobole',
  'Biotite',
  'Brookite',
  'Calcic pyroxene',
  'Calcite',
  'Carbon',
  'Carbonates',
  'Cassiterite',
  'Celestine',
  'Celsian',
  'Chain silicates',
  'Chalcocite',
  'Chalcopyrite',
  'Corundum',
  'Cristobalite',
  'Cummingtonite',
  'Diamond',
  'Diaspore',
  'Diopside',
  'Dolomite',
  'Ekermannite',
  'Enstatite',
  'Epidote',
  'Epidote Group',
  'Feldspar',
  'Fe - Mg clinoamphibole',
  'Ferrosilite',
  'Fe - Ti oxide',
  'Galena',
  'Garnet',
  'Gedrite',
  'Gibbsite',
  'Glauconite',
  'Glaucophane',
  'Grunerite',
  'Gypsum',
  'Hedenbergite',
  'Hematite',
  'Hercynite',
  'Hornblende',
  'Humite',
  'Hydroxides',
  'Jadeite',
  'Kaersutite',
  'Kalsilite',
  'Kaolinite',
  'Katophorite',
  'K feldspar',
  'K - feldspar',
  'Kyanite',
  'Labradorite',
  'Larnite',
  'Lawsonite',
  'Lepidocrocite',
  'Lepidolite',
  'Leucite',
  'Limonite',
  'Magnesite',
  'Magnetite',
  'Margarite',
  'Melilite',
  'Merwinite',
  'Mica',
  'Microcline',
  'Monazite',
  'Montmorillonite',
  'Mullite',
  'Muscovite',
  'Native Elements',
  'Nepheline',
  'Oligoclase',
  'Olivine',
  'Omphacite',
  'Opaque',
  'Orthoamphibole',
  'Ortho - and Ring Silicates',
  'Orthoclase',
  'Orthopyroxene',
  'Oxides',
  'Paragonite',
  'Periclase',
  'Perovskite',
  'Perthite',
  'Phengite',
  'Phlogopite',
  'Phosphates',
  'Piemontite',
  'Plagioclase',
  'Prehnite',
  'Pumpellyite',
  'Pyrite',
  'Pyroxmangite',
  'Pyrrhotite',
  'Quartz',
  'Rankinite',
  'Rhodochrosite',
  'Rhodonite',
  'Richterite',
  'Riebeckite',
  'Rutile',
  'Sanidine',
  'Sapphirine',
  'Scapolite',
  'Sericite',
  'Spinel',
  'Spinel Group',
  'Spodumene',
  'Spurrite',
  'Staurolite',
  'Stilpnomelane',
  'Sulphates',
  'Sulphides',
  'Talc',
  'Tectosilicates',
  'Tilleyite',
  'Titanite',
  'Topaz',
  'Tourmaline',
  'Tremolite',
  'Tridymite',
  'Vermiculite',
  'Vesuvanite',
  'White Mica',
  'Wollastonite',
  'Wonesite',
  'Xenotime',
  'Zeolite',
  'Zircon',
  'Zoisite'
]

export const SAMPLE_PARAMETER_TYPES = [
  'Weight',
  'Connected Porosity',
  'Unconnected Porosity',
  'Total Porosity',
  'Density',
  'Permeability (Gas)',
  'Permeability (Water)',
  'Temperature',
  'Humidity',
  'Fluid Saturation',
  'Stress',
  'Other'
]

export const FRACTION_UNITS = [
  'Vol%',
  'Wt%',
  '%',
  'ppm',
  'ppb'
]
