// LAPS Schema Enum Values
// IMPORTANT: These values must match the old app exactly
// Reference: /experimental/add_experiment.php and /experimental/experimental_data_fields.js

// ===== FACILITY TYPES =====
// From old app lines 252-258
export const FACILITY_TYPES = [
  'University Lab',
  'Government Facility',
  'Private Industry Lab',
  'Shared Facility',
  'Military',
  'Other'
]

// ===== APPARATUS TYPES =====
// From old app - 47 types plus "Other Apparatus"
export const APPARATUS_TYPES = [
  'Uniaxial',
  'Triaxial (conventional)',
  'Biaxial',
  'True Triaxial',
  'Direct Shear',
  'Shear Box',
  'Rotary Shear Friction Apparatus',
  'Creep Cell',
  'Indentation Cell',
  'Piston Cylinder',
  'Multi Anvil',
  'D-DIA',
  'Rotational Drickamer Apparatus (RDA)',
  'Large Volume Torsion Apparatus (LVT)',
  '1 Atm Gas Mixing Furnace',
  'Vacuum Furnace',
  'Other Gas Medium Apparatus',
  'Other Solid Medium Apparatus',
  'Other Liquid Medium Apparatus',
  'Vickers Hardness Tester',
  'Nanoindenter',
  'Diamond Anvil Cell',
  'Brazilian Test',
  'Paterson Apparatus',
  'Heard Apparatus',
  'Griggs Apparatus',
  'Schmidt Hammer',
  'Split Hopkinson Pressure Bar',
  'Double Torsion apparatus',
  'Point Load',
  'Atomic Force Microscope',
  'Rheometer',
  'Permeameter',
  'Pycnometer',
  'Viscosimeter',
  'Laser Profilometer',
  'Light Interferometer',
  'Load Stamp',
  'Chevron Notch Test',
  'Paris-Edinburgh Rig',
  'NER Rig',
  'Sanchez Rig',
  'Micro-Deformation Cell',
  'Ancillary Equipment',
  'Commercial Apparatus',
  'Other Apparatus'
]

// ===== APPARATUS FEATURES =====
// From old app lines 520-589 - all 59 features
export const APPARATUS_FEATURES = [
  'Loading',
  'Unloading',
  'Heating',
  'Cooling',
  'High Temperature',
  'Ultra-High Temperature',
  'Low Temperature',
  'Sub-Zero Temperature',
  'High Pressure',
  'Ultra-High Pressure',
  'Hydrostatic Tests',
  'HIP',
  'Synthesis',
  'Deposition/Evaporation',
  'Mineral Reactions',
  'Hydrothermal Reactions',
  'Elasticity',
  'Local Axial Strain',
  'Local Radial Strain',
  'Elastic Moduli',
  'Yield Strength',
  'Failure Strength',
  'Strength',
  'Extension',
  'Creep',
  'Friction',
  'Frictional Sliding',
  'Slide Hold Slide',
  'Stepping',
  'Pure Shear',
  'Simple Shear',
  'Rotary Shear',
  'Torsion',
  'Viscosity',
  'Indentation',
  'Hardness',
  'Dynamic Tests',
  'Hydraulic Fracturing',
  'Hydrothermal Fracturing',
  'Shockwave',
  'Reactive Flow',
  'Pore Fluid Control',
  'Pore Fluid Chemistry',
  'Pore Volume Compaction',
  'Storage Capacity',
  'Permeability',
  'Steady-State Permeability',
  'Transient Permeability',
  'Hydraulic Conductivity',
  'Drained/Undrained Pore Fluid',
  'Uniaxial Stress/Strain',
  'Biaxial Stress/Strain',
  'Triaxial Stress/Strain',
  'Differential Stress',
  'True Triaxial',
  'Resistivity',
  'Electrical Resistivity',
  'Electrical Capacitance',
  'Streaming Potential',
  'Acoustic Velocity',
  'Acoustic Events',
  'P-Wave Velocity',
  'S-Wave Velocity',
  'Source Location',
  'Tomography',
  'In-Situ X-Ray',
  'Infrared',
  'Raman',
  'Visual',
  'Other'
]

// ===== APPARATUS PARAMETER TYPES =====
// From old app
export const PARAMETER_TYPES = [
  'Confining Pressure Pc',
  'Pore Pressure Pp',
  'Differential Stress σ1-σ3',
  'Maximum Stress σ1',
  'Intermediate Stress σ2',
  'Minimum Stress σ3',
  'Temperature T',
  'Displacement',
  'Strain Rate',
  'Force',
  'Torque',
  'RPM',
  'Frequency',
  'Amplitude',
  'Sample Diameter',
  'Sample Length',
  'Other'
]

// ===== UNIT TYPES =====
// From old app lines 2888-2930 and 1417-1460 (same list used in multiple places)
export const UNIT_TYPES = [
  'degC',
  'degK',
  'sec',
  'min',
  'hour',
  'Volt',
  'mV',
  'Amperage',
  'mA',
  'Ohm',
  'Pa',
  'MPa',
  'GPa',
  'bar',
  'kbar',
  'N',
  'kN',
  'g',
  'mg',
  'μg',
  'm',
  'cm',
  'mm',
  'μm',
  'Hz',
  'kHz',
  'MHz',
  'Pa·s',
  'Darcy',
  'mDarcy',
  'm-1',
  'm2',
  'milistrain',
  'mm·sec-1',
  'N·sec-1',
  'sec-1',
  'kN·mm-1',
  '%',
  'count',
  'cc',
  'mm3'
]

// ===== UNIT PREFIXES =====
// From old app lines 2936-2950
export const UNIT_PREFIXES = [
  '1E+6',
  '1E+5',
  '1E+4',
  '1E+3',
  '1E+2',
  '1E+1',
  '-',
  '1E-1',
  '1E-2',
  '1E-3',
  '1E-4',
  '1E-5',
  '1E-6'
]

// ===== DOCUMENT TYPES =====
export const DOCUMENT_TYPES = [
  'Picture',
  'Diagram',
  'Manual',
  'Data',
  'Software',
  'Other'
]

// ===== DOCUMENT FORMATS =====
export const DOCUMENT_FORMATS = [
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'csv',
  'txt',
  'jpg',
  'jpeg',
  'png',
  'gif',
  'tif',
  'tiff',
  'zip',
  'rar',
  'Other'
]

// ===== SAMPLE ENUMS =====

// Material Types - from old app lines 2560-2574
export const MATERIAL_TYPES = [
  'Glass',
  'Ice',
  'Ceramic',
  'Plastic',
  'Metal',
  'Soil',
  'Mineral',
  'Igneous Rock',
  'Sedimentary Rock',
  'Metamorphic Rock',
  'Epos Lithologies',
  'Standards',
  'Commodity'
]

// Material State - from old app lines 2590-2598
export const MATERIAL_STATES = [
  'Homogeneous',
  'Heterogeneous',
  'Powder/Gauge',
  'Discontinuous',
  'Continuous',
  'Composite'
]

// Provenance Source - from old app lines 2655-2659 (NO "Other" option!)
export const PROVENANCE_SOURCES = [
  'Surface',
  'Quarry',
  'Well'
]

// Mineral Phase Unit - from old app lines 2829-2834
export const FRACTION_UNITS = [
  'Vol%',
  'Mol%',
  'Wt%',
  'MPa'
]

// Sample Parameter Variables - from old app lines 2857-2870
export const SAMPLE_PARAMETER_TYPES = [
  'Weight',
  'Connected Porosity',
  'Unconnected Porosity',
  'Total Porosity',
  'Density',
  'Permeability (Gas)',
  'Permeability (Water)',
  'Temperature',
  'Humidity',
  'Fluid Saturation',
  'Stress',
  'Other'
]

// Mineral Types - from old app sourceSelectMineral
export const MINERAL_TYPES = [
  'Other',
  'Actinolite',
  'Aegirine',
  'Albite',
  'Alkali - feldspar',
  'Amphibole',
  'Andesine',
  'Annite',
  'Anorthite',
  'Apatite',
  'Apophyllite',
  'Astrophyllite',
  'Augite',
  'Axinite',
  'Baryte',
  'Beryl',
  'Biopyribole',
  'Biopyrobole',
  'Biotite',
  'Brookite',
  'Calcic pyroxene',
  'Calcite',
  'Carbon',
  'Carbonates',
  'Cassiterite',
  'Celestine',
  'Celsian',
  'Chain silicates',
  'Chalcocite',
  'Chalcopyrite',
  'Corundum',
  'Cristobalite',
  'Cummingtonite',
  'Diamond',
  'Diaspore',
  'Diopside',
  'Dolomite',
  'Ekermannite',
  'Enstatite',
  'Epidote',
  'Epidote Group',
  'Feldspar',
  'Fe - Mg clinoamphibole',
  'Ferrosilite',
  'Fe - Ti oxide',
  'Galena',
  'Garnet',
  'Gedrite',
  'Gibbsite',
  'Glauconite',
  'Glaucophane',
  'Grunerite',
  'Gypsum',
  'Hedenbergite',
  'Hematite',
  'Hercynite',
  'Hornblende',
  'Humite',
  'Hydroxides',
  'Jadeite',
  'Kaersutite',
  'Kalsilite',
  'Kaolinite',
  'Katophorite',
  'K feldspar',
  'K - feldspar',
  'Kyanite',
  'Labradorite',
  'Larnite',
  'Lawsonite',
  'Lepidocrocite',
  'Lepidolite',
  'Leucite',
  'Limonite',
  'Magnesite',
  'Magnetite',
  'Margarite',
  'Melilite',
  'Merwinite',
  'Mica',
  'Microcline',
  'Monazite',
  'Montmorillonite',
  'Mullite',
  'Muscovite',
  'Native Elements',
  'Nepheline',
  'Oligoclase',
  'Olivine',
  'Omphacite',
  'Opaque',
  'Orthoamphibole',
  'Ortho - and Ring Silicates',
  'Orthoclase',
  'Orthopyroxene',
  'Oxides',
  'Paragonite',
  'Periclase',
  'Perovskite',
  'Perthite',
  'Phengite',
  'Phlogopite',
  'Phosphates',
  'Piemontite',
  'Plagioclase',
  'Prehnite',
  'Pumpellyite',
  'Pyrite',
  'Pyroxmangite',
  'Pyrrhotite',
  'Quartz',
  'Rankinite',
  'Rhodochrosite',
  'Rhodonite',
  'Richterite',
  'Riebeckite',
  'Rutile',
  'Sanidine',
  'Sapphirine',
  'Scapolite',
  'Sericite',
  'Spinel',
  'Spinel Group',
  'Spodumene',
  'Spurrite',
  'Staurolite',
  'Stilpnomelane',
  'Sulphates',
  'Sulphides',
  'Talc',
  'Tectosilicates',
  'Tilleyite',
  'Titanite',
  'Topaz',
  'Tourmaline',
  'Tremolite',
  'Tridymite',
  'Vermiculite',
  'Vesuvanite',
  'White Mica',
  'Wollastonite',
  'Wonesite',
  'Xenotime',
  'Zeolite',
  'Zircon',
  'Zoisite'
]

// Soil Types - from old app sourceSelectSoil
export const SOIL_TYPES = [
  'Other',
  'Bentonite'
]

// Igneous Rock Types - from old app sourceSelectIgneous
export const IGNEOUS_ROCK_TYPES = [
  'Other',
  'alkali feldspar granite',
  'andesite',
  'anorthosite',
  'aplite',
  'basalt',
  'diabase',
  'diorite',
  'dunite',
  'gabbro',
  'granite',
  'granodiorite',
  'harzburgite',
  'kimberlite',
  'komatiite',
  'lamprophyre',
  'lapilli tuff',
  'lherzolite',
  'monzonite',
  'norite',
  'obsidian',
  'pegmatite',
  'peridotite',
  'phonolite',
  'pumice',
  'pyroxenite',
  'quartz monzonite',
  'rhyolite',
  'scoria',
  'syenite',
  'tonalite',
  'trachyandesite',
  'trachyte',
  'troctolite',
  'tuff',
  'tuff breccia',
  'wehrlite'
]

// Sedimentary Rock Types - from old app sourceSelectSedimentary
export const SEDIMENTARY_ROCK_TYPES = [
  'Other',
  'argillite',
  'arkose',
  'breccia',
  'chalk',
  'chert',
  'claystone',
  'coal',
  'conglomerate',
  'coquina',
  'diatomite',
  'dolomite',
  'dolostone',
  'evaporite',
  'flint',
  'graywacke',
  'gypsum rock',
  'ironite formation',
  'limestone',
  'marl',
  'mudstone',
  'oil shale',
  'ite',
  'organic',
  'phosphatic',
  'rock salt',
  'sandstone',
  'shale',
  'siltstone',
  'travertine',
  'volcaniclastic',
  'wackestone'
]

// Metamorphic Rock Types - from old app sourceSelectMetamorphic
export const METAMORPHIC_ROCK_TYPES = [
  'Other',
  'amphibolite',
  'anthracite',
  'blackwall',
  'blueschist',
  'cataclasite',
  'eclogite',
  'garnetite',
  'glaucophanite',
  'gneiss',
  'granofels',
  'granulite',
  'greenstone',
  'greenschist',
  'hornfels',
  'marble',
  'metaarkose',
  'metabasite',
  'metacarbonate',
  'metagranite',
  'metagraywacke',
  'metaigneous',
  'meta-iron formation',
  'metapelite',
  'metasandstone',
  'meta-ultramafic',
  'migmatite',
  'mylonite',
  'orthogneiss',
  'paragneiss',
  'phyllite',
  'phyllonite',
  'pseudotachylyte',
  'pyroxenite',
  'quartzite',
  'rodingite',
  'schist',
  'serpentinite',
  'skarn',
  'slate',
  'soapstone',
  'whiteschist'
]

// Epos Lithology Types - from old app sourceSelectEpos (extensive list)
export const EPOS_LITHOLOGY_TYPES = [
  'Other',
  'acidic_igneous_material',
  'acidic_igneous_rock',
  'alkali_feldspar_granite',
  'alkali_feldspar_rhyolite',
  'alkali_feldspar_syenite',
  'alkali_feldspar_syenitic_rock',
  'alkali_feldspar_trachyte',
  'alkali_feldspar_trachytic_rock',
  'alkali - olivine_basalt',
  'amphibolite',
  'andesite',
  'anorthosite',
  'anorthositic_rock',
  'anthracite_coal',
  'anthropogenic_material',
  'anthropogenic_unconsolidated_material',
  'aphanite',
  'aplite',
  'arenite',
  'ash_and_lapilli',
  'ash_breccia_bomb_or_block_tephra',
  'ash_tuff_lapillistone_and_lapilli_tuff',
  'basalt',
  'basanite',
  'basanitic_foidite',
  'basic_igneous_material',
  'basic_igneous_rock',
  'bauxite',
  'biogenic_sediment',
  'biogenic_silica_sedimentary_rock',
  'bituminous_coal',
  'boninite',
  'boulder_gravel_size_sediment',
  'boundstone',
  'breccia',
  'breccia_gouge_series',
  'calcarite_carbonate_sediment',
  'calcareous_carbonate_sedimentary_material',
  'calcareous_carbonate_sedimentary_rock',
  'calclite',
  'calciumite',
  'calcite calciumite calcium calcium calcium calcium_calcium',
  'calcium car',
  'calcium te calcium te calcium te calcium te calcium te',
  'calcium te calcium te calcium te calcium te',
  'calcium te calcium te calcium te',
  'calcium te calcium te',
  'calcium te',
  'car bonite',
  'carbonate_mud',
  'carbonate_mudstone',
  'carbonate_ooze',
  'carbonate_rich_mud',
  'carbonate_rich_mudstone',
  'carbonate_sediment',
  'carbonate_sedimentary_material',
  'carbonate_sedimentary_rock',
  'carbonate_wackestone',
  'carbonite',
  'cataclasite_series',
  'chalk',
  'chemical_sedimentary_material',
  'chlorite_actinolite_epidote_metamorphic_rock',
  'clastic_conglomerate',
  'clastic_mudstone',
  'clastic_sandstone',
  'clastic_sediment',
  'clastic_sedimentary_material',
  'clastic_sedimentary_rock',
  'clay',
  'claystone',
  'coal',
  'cobble_gravel_size_sediment',
  'composite_genesis_material',
  'composite_genesis_rock',
  'compound_material',
  'crystalline_carbonate',
  'dacite',
  'diamictite',
  'diamicton',
  'diorite',
  'dioritic_rock',
  'dioritoid',
  'doleritic_rock',
  'dolomitic_or_magnesian_sedimentary_material',
  'dolomitic_or_magnesian_sedimentary_rock',
  'dolomitic_sediment',
  'doloite',
  'dolostone',
  'duricrust',
  'eclogite',
  'evaporite',
  'exotic_alkaline_rock',
  'exotic_composition_igneous_rock',
  'exotic_evaporite',
  'fault_related_material',
  'fine_grained_igneous_rock',
  'foid_bearing_alkali_feldspar_syenite',
  'foid_bearing_alkali_feldspar_trachyte',
  'foid_bearing_anorthosite',
  'foid_bearing_diorite',
  'foid_bearing_gabbro',
  'foid_bearing_latite',
  'foid_bearing_monzodiorite',
  'foid_bearing_monzogabbro',
  'foid_bearing_monzonite',
  'foid_bearing_syenite',
  'foid_bearing_trachyte',
  'foid_diorite',
  'foid_dioritoid',
  'foid_gabbro',
  'foid_gabbroid',
  'foid_monzodiorite',
  'foid_monzogabbro',
  'foid_monzosyenite',
  'foid_syenite',
  'foid_syenitoid',
  'foidite',
  'foiditoid',
  'foidolite',
  'foliated_metamorphic_rock',
  'fragmental_igneous_material',
  'fragmental_igneous_rock',
  'framestone',
  'gabbro',
  'gabbroic_rock',
  'gabbroid',
  'generic_conglomerate',
  'generic_mudstone',
  'generic_sandstone',
  'glass_rich_igneous_rock',
  'glassy_igneous_rock',
  'glaucophane_lawsonite_epidote_metamorphic_rock',
  'gneiss',
  'grainstone',
  'granite',
  'granitoid',
  'granodiorite',
  'granofels',
  'granulite',
  'gravel',
  'gravel_size_sediment',
  'ite',
  'high_magnesium_fine_grained_igneous_rocks',
  'hornblendite',
  'hornfels',
  'hybrid_sediment',
  'hybrid_sedimentary_rock',
  'igneous_material',
  'igneous_rock',
  'impact_generated_material',
  'impure_calcarite_carbonate_sediment',
  'impure_carbonate_sediment',
  'impure_carbonate_sedimentary_rock',
  'impure_dolomitic_sediment',
  'impure_dolostone',
  'impure_limestone',
  'intermediate_composition_igneous_material',
  'intermediate_composition_igneous_rock',
  'iron_rich_sediment',
  'iron_rich_sedimentary_material',
  'iron_rich_sedimentary_rock',
  'kalsilitic_and_melilitic_rock',
  'komatiitic_rock',
  'latite',
  'latitic_rock',
  'lignite',
  'limestone',
  'marble',
  'material_formed_in_surficial_environment',
  'metamorphic_rock',
  'metasomatic_rock',
  'mica_schist',
  'migmatite',
  'monzodiorite',
  'monzodioritic_rock',
  'monzogabbro',
  'monzogabbroic_rock',
  'monzogranite',
  'monzonite',
  'monzonitic_rock',
  'mud',
  'mud_size_sediment',
  'mylonitic_rock',
  'natural_unconsolidated_material',
  'non_clastic_siliceous_sediment',
  'non_clastic_siliceous_sedimentary_material',
  'non_clastic_siliceous_sedimentary_rock',
  'ooze',
  'organic_bearing_mudstone',
  'organic_rich_sediment',
  'organic_rich_sedimentary_material',
  'organic_rich_sedimentary_rock',
  'orthogneiss',
  'packstone',
  'paragneiss',
  'peat',
  'pegmatite',
  'peridotite',
  'phaneritic_igneous_rock',
  'phonolite',
  'phonolitic_basanite',
  'phonolitic_foidite',
  'phonolitic_tephrite',
  'phonolitoid',
  'phosphate_rich_sediment',
  'phosphate_rich_sedimentary_material',
  'phosphorite',
  'phyllite',
  'phyllonite',
  'porphyry',
  'pure_calcarite_carbonate_sediment',
  'pure_carbonate_mudstone',
  'pure_carbonate_sediment',
  'pure_carbonate_sedimentary_rock',
  'pure_dolomitic_sediment',
  'pyroclastic_material',
  'pyroclastic_rock',
  'pyroxenite',
  'quartz_alkali_feldspar_syenite',
  'quartz_alkali_feldspar_trachyte',
  'quartz_anorthosite',
  'quartz_diorite',
  'quartz_gabbro',
  'quartz_latite',
  'quartz_monzodiorite',
  'quartz_monzogabbro',
  'quartz_monzonite',
  'quartz_rich_igneous_rock',
  'quartz_syenite',
  'quartz_trachyte',
  'quartzite',
  'residual_material',
  'rhyolite',
  'rhyolitoid',
  'rock',
  'rock_gypsum_or_anhydrite',
  'rock_salt',
  'sand',
  'sand_size_sediment',
  'sapropel',
  'schist',
  'sediment',
  'sedimentary_material',
  'sedimentary_rock',
  'serpentinite',
  'shale',
  'silicate_mud',
  'silicate_mudstone',
  'siliceous_ite',
  'silt',
  'siltstone',
  'skarn',
  'slate',
  'spilite',
  'syenite',
  'syenitic_rock',
  'syenitoid',
  'syenogranite',
  'tephra',
  'tephrite',
  'tephritic_foidite',
  'tephritic_phonolite',
  'tephritoid',
  'tholeiitic_basalt',
  'tonalite',
  'trachyte',
  'trachytic_rock',
  'trachytoid',
  'travertine',
  'tuff_breccia_agglomerate_or_pyroclastic_breccia',
  'tuffite',
  'ultrabasic_igneous_rock',
  'ultramafic_igneous_rock',
  'unconsolidated_material',
  'wacke'
]

// Lab Standards - from old app sourceSelectStandards
export const LAB_STANDARDS = [
  'Other',
  'Austin Chalk',
  'Berea Sandstone',
  'Carrara Marble',
  'Indiana Limestone',
  'Frederick Maryland Diabase',
  'Heavitree Quartzite',
  'Solnhofen Limestone',
  'Simpson Quartzite',
  'Black Hills Quartzite',
  'Sioux Quartzite',
  'Cheshire Quartzite',
  'Arkansas Novaculite',
  'Westerley Granite'
]

// Commodity Types - from old app sourceSelectCommodity (extensive list)
export const COMMODITY_TYPES = [
  'Other',
  'agate',
  'aggregate',
  'alumina',
  'aluminium',
  'aluminosilicate',
  'alunite',
  'amazonite',
  'amber',
  'amethyst',
  'andalusite',
  'anhydrite',
  'anthophyllite',
  'anthracite',
  'antimony',
  'apatite',
  'apatite - gemstone',
  'aquamarine',
  'arsenic',
  'asbestos',
  'asbestos - amphibole',
  'asbestos - serpentine',
  'asphalt',
  'barium',
  'baryte',
  'basalt',
  'base - metal',
  'bauxite',
  'bentonite',
  'beryl',
  'beryllium',
  'bismuth',
  'black - coal',
  'borate',
  'boron',
  'brick - clay',
  'bromine',
  'brown - coal',
  'cadmium',
  'calcite',
  'carbonaceous - material',
  'carnallite',
  'carnelian',
  'cassiterite - gemstone',
  'cerium',
  'cesium',
  'chalcedony',
  'chemical - compound - product',
  'chemical - oxide - product',
  'chert',
  'chlorite',
  'chrome',
  'chromite',
  'chromium',
  'chrysoberyl',
  'chrysoprase',
  'chrysotile',
  'citrine',
  'clay',
  'coal',
  'coal - bed - methane',
  'cobalt',
  'copper',
  'corundum',
  'corundum - gemstone',
  'crocidolite',
  'crushed - rock',
  'cryolite',
  'diamond',
  'diamond - gemstone',
  'diatomite',
  'dimension - stone',
  'diopside - enstatite',
  'dioptase',
  'direct - shipping - ore',
  'direct - use - commodity',
  'dumortierite',
  'dysprosium',
  'emerald',
  'epsomite',
  'erbium',
  'euclase',
  'europium',
  'evaporite',
  'feldspar',
  'feldspar - gemstone',
  'ferrous - metal',
  'fluorine',
  'fluorite',
  'foundry - sand',
  'frac - sand',
  'fullers - earth',
  'gadolinium',
  'gallium',
  'garnet',
  'garnet - gemstone',
  'gaseous - hydrocarbons',
  'gas - hydrate',
  'gemstones',
  'germanium',
  'glauconite',
  'gold',
  'granite',
  'graphite',
  'greenstone',
  'gypsum',
  'hafnium',
  'halloysite',
  'heavy - rare - earth - oxide',
  'heliodor',
  'hematite',
  'hematite - gemstone',
  'hematite - ore',
  'holmium',
  'hree',
  'ilmenite',
  'indium',
  'industrial - material',
  'industrial - mineral',
  'industrial - rock',
  'iodine',
  'iolite',
  'iridium',
  'iron',
  'iron - ore',
  'iron - oxide',
  'jade',
  'jarosite',
  'kaolin',
  'kornerupine',
  'kyanite',
  'kyanite - gemstone',
  'lanthanum',
  'laterite',
  'lazulite',
  'lead',
  'leucoxene',
  'light - rare - earth - oxide',
  'lime',
  'limestone',
  'liquid - hydrocarbons',
  'lithium',
  'lithium - oxide',
  'lree',
  'lutetium',
  'magnesia',
  'magnesite',
  'magnesium',
  'magnetite',
  'magnetite - ore',
  'malachite',
  'manganese',
  'manganese - ore',
  'marble',
  'mercury',
  'metal',
  'metalloid',
  'mica',
  'miscellaneous - dimension - stones',
  'molybdenite',
  'molybdenum',
  'monazite',
  'moonstone',
  'morganite',
  'moss - agate',
  'natural - secondary - aggregate',
  'neodymium',
  'nepheline - syenite',
  'nickel',
  'niobium',
  'niobium - pentoxide',
  'nitrate',
  'non - metal',
  'obsidian',
  'ochre',
  'oil',
  'oil - shale',
  'olivine',
  'olivine - gemstone',
  'onyx',
  'opal',
  'organic - material',
  'osmium',
  'palladium',
  'palygorskite',
  'peat',
  'perlite',
  'phenakite',
  'phosphate - rock',
  'phosphorous',
  'phosphorous - pentoxide',
  'platinum',
  'platinum - group',
  'potash',
  'potassium',
  'pozzolan',
  'praseodymium',
  'precious - metal',
  'prehnite',
  'primary - aggregate',
  'produced - commodity',
  'promethium',
  'pumice',
  'pyrite',
  'pyrophyllite',
  'quartz',
  'quartz - gemstone',
  'radium',
  'rare - earth - element',
  'rare - earth - oxide',
  'recycled - aggregate',
  'reservoir - gas',
  'rhenium',
  'rhodium',
  'rhodonite',
  'riprap',
  'rose - quartz',
  'rubidium',
  'ruby',
  'ruthenium',
  'rutile',
  'salt',
  'samarium',
  'sand',
  'sand - and - gravel',
  'sandstone',
  'saponite',
  'sapphire',
  'sapphirine',
  'scandium',
  'scapolite',
  'selenium',
  'sepiolite',
  'sericite',
  'serpentine',
  'shell - grit',
  'silica',
  'silica - gemstone',
  'silicon',
  'sillimanite',
  'silver',
  'sinhalite',
  'slate',
  'smokey - quartz',
  'soda - ash',
  'sodalite',
  'spectrolite',
  'spinel',
  'spinel - gemstone',
  'spodumene',
  'spongolite',
  'staurolite',
  'strontianite',
  'strontium',
  'sulphur',
  'sylvite',
  'talc',
  'tantalum',
  'tantalum - pentoxide',
  'tanzanite',
  'tar - sand',
  'tellurium',
  'terbium',
  'thallium',
  'thenardite',
  'thorium',
  'thulium',
  'tin',
  'titanium',
  'topaz',
  'tourmaline',
  'tremolite - actinolite',
  'tsavorite',
  'tungsten',
  'turquoise',
  'uranium',
  'uranium - oxide',
  'vanadium',
  'vanadium - pentoxide',
  'variscite',
  'vermiculite',
  'vesuvianite',
  'white - firing - clay',
  'wollastonite',
  'xenotime - gemstone',
  'ytterbium',
  'yttrium',
  'yttrium - oxide',
  'zeolite',
  'zinc',
  'zircon',
  'zircon - gemstone',
  'zirconia',
  'zirconium'
]

// Material types that use text input for name (instead of dropdown)
export const TEXT_INPUT_MATERIAL_TYPES = [
  'Glass',
  'Ice',
  'Ceramic',
  'Plastic',
  'Metal'
]

// Mapping of material type to label for the name field
export const MATERIAL_NAME_LABELS = {
  'Glass': 'Name',
  'Ice': 'Name',
  'Ceramic': 'Name',
  'Plastic': 'Name',
  'Metal': 'Name',
  'Soil': 'Soil Type',
  'Mineral': 'Mineral Name',
  'Igneous Rock': 'Igneous Rock',
  'Sedimentary Rock': 'Sedimentary Rock',
  'Metamorphic Rock': 'Metamorphic Rock',
  'Epos Lithologies': 'Epos Lithology',
  'Standards': 'Lab Standard',
  'Commodity': 'Commodity Name'
}

// Mapping of material type to dropdown options
export const MATERIAL_NAME_OPTIONS = {
  'Soil': SOIL_TYPES,
  'Mineral': MINERAL_TYPES,
  'Igneous Rock': IGNEOUS_ROCK_TYPES,
  'Sedimentary Rock': SEDIMENTARY_ROCK_TYPES,
  'Metamorphic Rock': METAMORPHIC_ROCK_TYPES,
  'Epos Lithologies': EPOS_LITHOLOGY_TYPES,
  'Standards': LAB_STANDARDS,
  'Commodity': COMMODITY_TYPES
}

// ===== EXPERIMENTAL SETUP ENUMS =====

// Geometry component types
export const GEOMETRY_COMPONENT_TYPES = [
  'Sample',
  'Jacket',
  'Forcing Block',
  'Spacer'
]

// Geometry shape options
export const GEOMETRY_SHAPES = [
  'Cylinder',
  'Rectangular',
  'Circular',
  'Precut',
  'Dogbone',
  'Split Cylinder',
  'Tube'
]

// Geometry material options
export const GEOMETRY_MATERIALS = [
  'Sample',
  'PET',
  'PVC',
  'PTFE',
  'Rubber',
  'Viton',
  'Copper',
  'Iron',
  'Nickel',
  'Gold',
  'Platinum',
  'Silver',
  'Alumina',
  'Porous Alumina',
  'Zirconia',
  'PZT'
]

// Dimension variable options
export const DIMENSION_VARIABLES = [
  'Length',
  'Diameter',
  'Width',
  'Span',
  'Height',
  'Wall Thickness',
  'Bore Diameter',
  'Fault Angle'
]

// ===== DAQ (Data Acquisition) ENUMS =====

// DAQ system types - from old app
export const DAQ_TYPES = [
  'Standard',
  'Conventional',
  'Proprietary'
]

// Channel Header Types - from old app lines 1084-1094
export const CHANNEL_HEADER_TYPES = [
  'Time',
  'Temperature',
  'Pressure',
  'Strain',
  'Displacement',
  'Stress',
  'Load',
  'Electrical',
  'Chemistry',
  'Other'
]

// Channel types (signal types) - from old app lines 1197-1206
export const CHANNEL_TYPES = [
  'Calculated',
  'Analog Input',
  'Analog Output',
  'Digital Input',
  'Digital Output',
  'System Data',
  'System Clock'
]

// Channel electrical configurations - from old app lines 1212-1222
export const CHANNEL_CONFIGURATIONS = [
  'System',
  'Differential',
  'Single Ended',
  'Referenced Single Ended',
  'Serial',
  'Parallel',
  'Single',
  'Line'
]

// Channel gain (amplification) options - from old app lines 1266-1276
export const CHANNEL_GAINS = [
  'x1',
  'x2',
  'x5',
  'x10',
  'x20',
  'x25',
  'x50',
  'x100'
]

// Channel numbers (0-32)
export const CHANNEL_NUMBERS = Array.from({ length: 33 }, (_, i) => String(i))

// Sensor/Actuator types - from old app lines 1291-1317
export const SENSOR_ACTUATOR_TYPES = [
  'Clock',
  'LVDT',
  'Load Cell',
  'Capacitive Load Cell',
  'Pressure Transducer',
  'Thermocouple',
  'Hall Sensor',
  'P-Wave Sensor',
  'S-Wave Sensor',
  'Encoder',
  'Strain Gauge',
  'Thermistor',
  'Force Gauge',
  'DCDT',
  'pH-Meter',
  'Flow Meter',
  '--',
  'Linear Motor',
  'Servo Motor',
  'Step Motor',
  'Actuator',
  'Heater',
  'Power',
  'Trigger'
]

// Sensor active/passive types - from old app lines 1349-1353
export const SENSOR_ACTIVE_PASSIVE_TYPES = [
  'Active',
  'Passive'
]

// IEEE Sensor Templates - from old app lines 1323-1341
export const IEEE_SENSOR_TEMPLATES = [
  'Accelerometer & Force',
  'Charge Amplifier (w/ attached accelerometer)',
  'Charge Amplifier (w/ attached force transducer)',
  'Microphone with built-in preamplifier',
  'Microphone Preamplfiers (w/ attached microphone)',
  'Microphones (capacitive)',
  'High-Level Voltage Output Sensors',
  'Current Loop Output Sensors',
  'Resistance Sensors',
  'Bridge Sensors',
  'LVDT/RVDT Sensors',
  'Strain Gage',
  'Thermocouple',
  'Resistance Temperature Detectors (RTDs)',
  'Thermistor',
  'Potentiometric Voltage Divider'
]

// Calibration Templates - from old app lines 1404-1411
export const CALIBRATION_TEMPLATES = [
  'Input:Unit',
  'Input@0:Input/Unit',
  '(a0:a1)(a2:a3)',
  'Base:Exponent',
  'Frequency:Amplitude'
]

// ===== DAQ CHANNEL HEADER DATA FIELDS =====
// From /experimental/experimental_data_fields.js
// This array drives the dynamic dropdown population for spec_a, spec_b, and unit
// based on the selected header type
export const DAQ_DATA_FIELDS = [
  // Time
  { headerType: 'Time', fieldVal: 'spec_a', selectVal: 'Absolute' },
  { headerType: 'Time', fieldVal: 'spec_a', selectVal: 'Relative' },
  { headerType: 'Time', fieldVal: 'spec_b', selectVal: 'Total' },
  { headerType: 'Time', fieldVal: 'spec_b', selectVal: 'Differential' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'sec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'min' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'hour' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'day' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'ysec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'msec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'UTC' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'dd-mm-yyyy' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'mm/dd/yy' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'hh-mm-ss' },
  // Temperature
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Room' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Sample' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Furnace' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Fluid' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Pore' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Vessel' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Top' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Bottom' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Average' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg C' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg K' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg F' },
  // Pressure
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Barometric' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Pore' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Effective' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Vessel' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Intensifier' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Upstream' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Downstream' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'bar' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'kPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'MPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'GPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'PSI' },
  // Strain
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Total' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Volumetric' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Rate' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: 'mStrain' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: 'Strain' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: '1/sec' },
  // Displacement
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Total' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Volumetric' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Rate' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Pore Pressure Intensifier' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Confining Pressure Intensifier' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Pore Volume' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Confining Volume' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'μm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'mm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'mm/s' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'inches' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'feet' },
  // Stress
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Normal' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'Pa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'KPa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'MPa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'GPa' },
  // Load
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Normal' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Load', fieldVal: 'unit', selectVal: 'N' },
  { headerType: 'Load', fieldVal: 'unit', selectVal: 'KN' },
  // Electrical
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Conductivity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Resistivity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Capacity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Spontaneous Potential' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'AC Voltage' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'DC Voltage' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Current' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Induction' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Pore Fluid' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Total' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Heating' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Cooling' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'μVolt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'mVolt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Volt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'A' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'mA' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'S' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'S/m' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'F' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Ω' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Ωm' },
  // Chemistry
  { headerType: 'Chemistry', fieldVal: 'spec_a', selectVal: 'Pore Fluid' },
  { headerType: 'Chemistry', fieldVal: 'spec_a', selectVal: 'Fluid' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'pH' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'pOH' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Na+' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'K+' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Ca++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Mg++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Sr++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'HCO3-' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'TOC' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'TIC' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'CO2(gas)' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'CO2(sol)' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'mol/L' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'mMol/L' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'ppm' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'cc' },
  // Other - extensive list of spec_a values (no spec_b)
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Acoustic Emissions' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Acoustic Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Amplitude' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Anisotropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Attenuation' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Bulk Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Capacitance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Centrifugal Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Chemical Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Coldness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Confining Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Current Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Downstream Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Dynamic Viscosity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Elasticity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Elastic Wave Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric charge' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric Charge Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric Current' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Resistance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Resistivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Fracture Toughness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Frequency' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Friction Coefficient' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Heat' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Hydraulic Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Impedance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Impulse' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Inductance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Intensity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Irradiance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Lame Parameter' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Length' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Linear Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Luminance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Field Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Flux' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass Fraction' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Moment of Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Moment of Inertia' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Momentum' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Permittivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Permeability' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Plane Angle' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: "Poisson's Ratio" },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'P-Wave Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Radiance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Radioactive Dose' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Reaction Rate' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Refractive Index' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Roughness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Shear Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Solid Angle' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Volume' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Spontaneous Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Strain' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Streaming Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Stress' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Charge Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Tension' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Temperature' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Temperature Gradient' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Conductance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Resistance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Resistivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Time' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Torque' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Upstream Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Volume' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Volumetric Flow Rate' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavelength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavenumber' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavevector' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Weight' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Work' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Yield Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: "Young's Modulus" }
]

// Helper function to get options for a specific header type and field
export function getDAQOptionsForHeader(headerType, fieldType) {
  if (!headerType) return []

  const options = DAQ_DATA_FIELDS
    .filter(df => df.headerType === headerType && df.fieldVal === fieldType)
    .map(df => df.selectVal)

  // Return unique values
  return [...new Set(options)]
}

// Contact affiliation roles
export const CONTACT_AFFILIATIONS = [
  'PI',
  'Co-PI',
  'Technician',
  'Student',
  'Postdoc',
  'Engineer',
  'Scientist',
  'Manager',
  'Director',
  'Other'
]

// ===== PROTOCOL ENUMS =====

// Protocol control variables - from old app edit_experiment.php lines 3493-3517
// These are the parameter variables for protocol steps
export const PROTOCOL_CONTROL_VARIABLES = [
  'Temperature T',
  'Confining Pressure Pc',
  'Pore Pressure Pp',
  'Time t',
  'Frequency',
  'Amplitude',
  'Stress σ1',
  'Strain ε1',
  'Strain Rate ε1/dt',
  'Displacement Δs1',
  'Force F2',
  'Stress σ2',
  'Strain ε2',
  'Strain Rate ε2/dt',
  'Displacement Δs2',
  'Force F2',
  'Stress σ3',
  'Strain ε3',
  'Strain Rate ε3/dt',
  'Displacement Δs3',
  'Force F3',
  'Saturation',
  'Humidity',
  'Count'
]
