// LAPS Schema Enum Values
// IMPORTANT: These values must match the old app exactly
// Reference: /experimental/add_experiment.php and /experimental/experimental_data_fields.js

// ===== FACILITY TYPES =====
// From old app lines 252-258
export const FACILITY_TYPES = [
  'Government Facility',
  'Military',
  'Private Industry Lab',
  'Shared Facility',
  'University Lab',
  'Other'
]

// ===== APPARATUS TYPES =====
// From old app - 47 types plus "Other Apparatus"
export const APPARATUS_TYPES = [
  '1 Atm Gas Mixing Furnace',
  'Ancillary Equipment',
  'Atomic Force Microscope',
  'Biaxial',
  'Brazilian Test',
  'Chevron Notch Test',
  'Commercial Apparatus',
  'Creep Cell',
  'D-DIA',
  'Diamond Anvil Cell',
  'Direct Shear',
  'Double Torsion apparatus',
  'Griggs Apparatus',
  'Heard Apparatus',
  'Indentation Cell',
  'Large Volume Torsion Apparatus (LVT)',
  'Laser Profilometer',
  'Light Interferometer',
  'Load Stamp',
  'Micro-Deformation Cell',
  'Multi Anvil',
  'Nanoindenter',
  'NER Rig',
  'Other Gas Medium Apparatus',
  'Other Liquid Medium Apparatus',
  'Other Solid Medium Apparatus',
  'Paris-Edinburgh Rig',
  'Paterson Apparatus',
  'Permeameter',
  'Piston Cylinder',
  'Point Load',
  'Pycnometer',
  'Rheometer',
  'Rotary Shear Friction Apparatus',
  'Rotational Drickamer Apparatus (RDA)',
  'Sanchez Rig',
  'Schmidt Hammer',
  'Shear Box',
  'Split Hopkinson Pressure Bar',
  'Triaxial (conventional)',
  'True Triaxial',
  'Uniaxial',
  'Vacuum Furnace',
  'Vickers Hardness Tester',
  'Viscosimeter',
  'Other Apparatus'
]

// ===== APPARATUS FEATURES =====
// All unique features from GROUPED_FEATURES (flat list for compatibility)
export const APPARATUS_FEATURES = [
  'Acoustic Events (AE)',
  'Acoustic Velocity',
  'AE Source Location',
  'Axial Strain',
  'Axial Stress',
  'Biaxial Stress/Strain',
  'Brittle-Ductile',
  'Brittle-Plastic',
  'Brittle-Viscous',
  'Cold Pressed',
  'Compaction (Pore Volume Compaction)',
  'Compression',
  'Conductivity (Electrical Conductivity)',
  'Cooling',
  'Creep & Rate dependent deformation',
  'Cyclic',
  'Deposition/Evaporation',
  'Differential Stress',
  'Drained/Undrained Pore Fluid',
  'Dynamic Deformation (Tests)',
  'EDS or WDS Probe Analyses',
  'Elastic Moduli',
  'Elasticity',
  'Electrical Capacitance',
  'Electron Microscopy (SEM, TEM)',
  'Extension',
  'Failure Strength',
  'Flow Strength',
  'Fluid storage capacity',
  'Fracture',
  'Friction',
  '(Frictional Sliding)',
  'Gel-synthesized',
  'General Shear',
  'Hardness',
  'Heating',
  'High Pressure',
  'High Temperature',
  'HIP (Hot Isostatic Pressing) Synthesis',
  'HIP Synthesized',
  'Hydraulic Conductivity',
  'Hydraulic Fracturing',
  'Hydrostatic',
  'Hydrothermal Fracturing',
  'Hydrothermal Reactions',
  'In-situ X-ray Diffraction',
  'Indentation',
  'Infrared Spectroscopy',
  'Lateral Strain(s)',
  'Lateral Stress(es)',
  'Loading',
  'Low Temperature',
  'Mineral Reactions',
  'Natural Gouge',
  'Natural Rock',
  'Optical Microscopy',
  'P-wave Velocity',
  'Permeable fluid flow',
  'Plastic',
  'Pore Fluid',
  'Pore Fluid Chemistry',
  'Pore Fluid Control',
  '(Pore Fluid) Permeability',
  'Pore Pressure',
  'Pure Shear',
  'Radial Strain',
  'Raman Spectroscopy',
  'Reactive Flow',
  'Resistivity (Electrical Resistivity)',
  'Rotary Shear',
  'S-wave Velocity',
  'Shear Strain',
  'Shock Deformation (shockwave)',
  'Simple Shear',
  'Single Crystal',
  'Sintered',
  'Slide-Hold-Slide',
  'Steady-state fluid flow (permeability)',
  'Stepping',
  'Strain',
  'Streaming Potential',
  'Strength',
  'Stress',
  'Sub-Zero Temperature',
  'Synthetic Gouge',
  'Tension',
  'Tomography',
  'Torsion',
  'Transient fluid flow (permeability)',
  'Triaxial Stress/Strain',
  'True Triaxial Stress/Strain',
  'Ultra-high Pressure',
  'Ultra-High Temperature',
  'Uniaxial Stress/Strain',
  'Unloading',
  'Viscous Deformation',
  'Visual',
  'X-ray Diffraction',
  'Yield Strength',
  'Other'
]

// ===== GROUPED APPARATUS/TEST FEATURES =====
// Features organized by category from experimental_features.xlsx
// NOTE: Some features appear in multiple categories - that's intentional.
// When a feature is selected, it highlights in ALL categories where it appears,
// but is only saved once in the data.
export const GROUPED_FEATURES = [
  {
    name: 'Type of Experiment',
    features: [
      'Loading',
      'Unloading',
      'Uniaxial Stress/Strain',
      'Biaxial Stress/Strain',
      'Triaxial Stress/Strain',
      'True Triaxial Stress/Strain',
      'Pure Shear',
      'Simple Shear',
      'General Shear',
      'Rotary Shear',
      'Indentation',
      'Hydraulic Fracturing',
      'Hydrothermal Fracturing',
      'Stepping',
      'Cyclic',
      'Slide-Hold-Slide',
      'Dynamic Deformation (Tests)',
      'Shock Deformation (shockwave)'
    ]
  },
  {
    name: 'Mechanical Behavior',
    features: [
      'Elasticity',
      'Fracture',
      'Compaction (Pore Volume Compaction)',
      'Friction',
      '(Frictional Sliding)',
      'Plastic',
      'Hardness',
      'Viscous Deformation',
      'Creep & Rate dependent deformation',
      'Brittle-Plastic',
      'Brittle-Ductile',
      'Brittle-Viscous'
    ]
  },
  {
    name: 'Mechanical Measurements',
    features: [
      'Stress',
      'Strain',
      'Axial Stress',
      'Lateral Stress(es)',
      'Differential Stress',
      'Strength',
      'Yield Strength',
      'Failure Strength',
      'Flow Strength',
      'Axial Strain',
      'Radial Strain',
      'Lateral Strain(s)',
      'Shear Strain',
      'Elastic Moduli',
      'Acoustic Velocity',
      'Acoustic Events (AE)',
      'P-wave Velocity',
      'S-wave Velocity',
      'AE Source Location',
      '(Pore Fluid) Permeability',
      'Fluid storage capacity',
      'Steady-state fluid flow (permeability)',
      'Transient fluid flow (permeability)',
      'Hydraulic Conductivity',
      'Resistivity (Electrical Resistivity)',
      'Conductivity (Electrical Conductivity)',
      'Electrical Capacitance',
      'Streaming Potential'
    ]
  },
  {
    name: 'Sample / Starting Material',
    features: [
      'Single Crystal',
      'Natural Rock',
      'Natural Gouge',
      'Synthetic Gouge',
      'Sintered',
      'Gel-synthesized',
      'Cold Pressed',
      'HIP Synthesized'
    ]
  },
  {
    name: 'Sample / Starting Material Characterization',
    features: [
      'Visual',
      'Optical Microscopy',
      'Electron Microscopy (SEM, TEM)',
      'X-ray Diffraction',
      'EDS or WDS Probe Analyses',
      'Infrared Spectroscopy',
      'Raman Spectroscopy',
      'Tomography',
      'In-situ X-ray Diffraction',
      'Other'
    ]
  },
  {
    name: 'Pore Fluids and Geochemical Processes',
    features: [
      'Pore Fluid',
      'Permeable fluid flow',
      'Hydrothermal Reactions',
      'Mineral Reactions',
      'Deposition/Evaporation',
      'Reactive Flow'
    ]
  },
  {
    name: 'Experimental Conditions (Pressure / Stress)',
    features: [
      'High Pressure',
      'Ultra-high Pressure',
      'Hydrostatic',
      'HIP (Hot Isostatic Pressing) Synthesis',
      'Pore Pressure',
      'Drained/Undrained Pore Fluid',
      'Pore Fluid Control',
      'Pore Fluid Chemistry',
      'Compression',
      'Extension',
      'Tension',
      'Torsion'
    ]
  },
  {
    name: 'Experimental Conditions (Thermal)',
    features: [
      'Heating',
      'Cooling',
      'High Temperature',
      'Ultra-High Temperature',
      'Low Temperature',
      'Sub-Zero Temperature'
    ]
  }
]

// ===== APPARATUS PARAMETER TYPES =====
// From old app
export const PARAMETER_TYPES = [
  'σ1-Displacement',
  'σ1-Load',
  'σ2-Displacement',
  'σ2-Load',
  'σ3-Displacement',
  'σ3-Load',
  'Confining Pressure',
  'Displacement Rate',
  'Effective Pressure',
  'Loading Rate',
  'Permeability',
  'Pore Pressure',
  'Sample Diameter',
  'Sample Length',
  'Stiffness',
  'Temperature'
]

// ===== UNIT TYPES =====
// From old app lines 2888-2930 and 1417-1460 (same list used in multiple places)
export const UNIT_TYPES = [
  '%',
  'Amperage',
  'bar',
  'cc',
  'cm',
  'count',
  'Darcy',
  'degC',
  'degK',
  'g',
  'μg',
  'GPa',
  'hour',
  'Hz',
  'kbar',
  'kHz',
  'kN',
  'kN·mm-1',
  'm',
  'μm',
  'm-1',
  'm2',
  'mA',
  'mDarcy',
  'mg',
  'MHz',
  'milistrain',
  'min',
  'mm',
  'mm·sec-1',
  'mm3',
  'MPa',
  'mV',
  'N',
  'N·sec-1',
  'Ohm',
  'Pa',
  'Pa·s',
  'sec',
  'sec-1',
  'Volt'
]

// ===== UNIT PREFIXES =====
// From old app lines 2936-2950
export const UNIT_PREFIXES = [
  '1E+6',
  '1E+5',
  '1E+4',
  '1E+3',
  '1E+2',
  '1E+1',
  '-',
  '1E-1',
  '1E-2',
  '1E-3',
  '1E-4',
  '1E-5',
  '1E-6'
]

// ===== DOCUMENT TYPES =====
// From old app add_experiment.php lines 676-684
export const DOCUMENT_TYPES = [
  'ASTM',
  'Data',
  'Diagram',
  'Manual',
  'Picture',
  'Publication',
  'Software',
  'Video',
  'Other'
]

// ===== DOCUMENT FORMATS =====
// From old app add_experiment.php lines 695-703
export const DOCUMENT_FORMATS = [
  'csv',
  'docx',
  'jpg',
  'pdf',
  'png',
  'rar',
  'txt',
  'zip',
  'Other'
]

// ===== SAMPLE ENUMS =====

// Material Types - from old app lines 2560-2574
export const MATERIAL_TYPES = [
  'Ceramic',
  'Commodity',
  'Epos Lithologies',
  'Glass',
  'Ice',
  'Igneous Rock',
  'Metal',
  'Metamorphic Rock',
  'Mineral',
  'Plastic',
  'Sedimentary Rock',
  'Soil',
  'Standards'
]

// Material State - from old app lines 2590-2598
export const MATERIAL_STATES = [
  'Composite',
  'Continuous',
  'Discontinuous',
  'Heterogeneous',
  'Homogeneous',
  'Powder/Gauge'
]

// Provenance Source - from old app lines 2655-2659 (NO "Other" option!)
export const PROVENANCE_SOURCES = [
  'Quarry',
  'Surface',
  'Well'
]

// Mineral Phase Unit - from old app lines 2829-2834
export const FRACTION_UNITS = [
  'Mol%',
  'MPa',
  'Vol%',
  'Wt%'
]

// Sample Parameter Variables - from old app lines 2857-2870
export const SAMPLE_PARAMETER_TYPES = [
  'Connected Porosity',
  'Density',
  'Fluid Saturation',
  'Humidity',
  'Permeability (Gas)',
  'Permeability (Water)',
  'Stress',
  'Temperature',
  'Total Porosity',
  'Unconnected Porosity',
  'Weight',
  'Other'
]

// Mineral Types - from old app sourceSelectMineral
export const MINERAL_TYPES = [
  'Actinolite',
  'Aegirine',
  'Albite',
  'Alkali - feldspar',
  'Amphibole',
  'Andesine',
  'Annite',
  'Anorthite',
  'Apatite',
  'Apophyllite',
  'Astrophyllite',
  'Augite',
  'Axinite',
  'Baryte',
  'Beryl',
  'Biopyribole',
  'Biopyrobole',
  'Biotite',
  'Brookite',
  'Calcic pyroxene',
  'Calcite',
  'Carbon',
  'Carbonates',
  'Cassiterite',
  'Celestine',
  'Celsian',
  'Chain silicates',
  'Chalcocite',
  'Chalcopyrite',
  'Corundum',
  'Cristobalite',
  'Cummingtonite',
  'Diamond',
  'Diaspore',
  'Diopside',
  'Dolomite',
  'Ekermannite',
  'Enstatite',
  'Epidote',
  'Epidote Group',
  'Fe - Mg clinoamphibole',
  'Fe - Ti oxide',
  'Feldspar',
  'Ferrosilite',
  'Galena',
  'Garnet',
  'Gedrite',
  'Gibbsite',
  'Glauconite',
  'Glaucophane',
  'Grunerite',
  'Gypsum',
  'Hedenbergite',
  'Hematite',
  'Hercynite',
  'Hornblende',
  'Humite',
  'Hydroxides',
  'Jadeite',
  'K - feldspar',
  'K feldspar',
  'Kaersutite',
  'Kalsilite',
  'Kaolinite',
  'Katophorite',
  'Kyanite',
  'Labradorite',
  'Larnite',
  'Lawsonite',
  'Lepidocrocite',
  'Lepidolite',
  'Leucite',
  'Limonite',
  'Magnesite',
  'Magnetite',
  'Margarite',
  'Melilite',
  'Merwinite',
  'Mica',
  'Microcline',
  'Monazite',
  'Montmorillonite',
  'Mullite',
  'Muscovite',
  'Native Elements',
  'Nepheline',
  'Oligoclase',
  'Olivine',
  'Omphacite',
  'Opaque',
  'Ortho - and Ring Silicates',
  'Orthoamphibole',
  'Orthoclase',
  'Orthopyroxene',
  'Oxides',
  'Paragonite',
  'Periclase',
  'Perovskite',
  'Perthite',
  'Phengite',
  'Phlogopite',
  'Phosphates',
  'Piemontite',
  'Plagioclase',
  'Prehnite',
  'Pumpellyite',
  'Pyrite',
  'Pyroxmangite',
  'Pyrrhotite',
  'Quartz',
  'Rankinite',
  'Rhodochrosite',
  'Rhodonite',
  'Richterite',
  'Riebeckite',
  'Rutile',
  'Sanidine',
  'Sapphirine',
  'Scapolite',
  'Sericite',
  'Spinel',
  'Spinel Group',
  'Spodumene',
  'Spurrite',
  'Staurolite',
  'Stilpnomelane',
  'Sulphates',
  'Sulphides',
  'Talc',
  'Tectosilicates',
  'Tilleyite',
  'Titanite',
  'Topaz',
  'Tourmaline',
  'Tremolite',
  'Tridymite',
  'Vermiculite',
  'Vesuvanite',
  'White Mica',
  'Wollastonite',
  'Wonesite',
  'Xenotime',
  'Zeolite',
  'Zircon',
  'Zoisite',
  'Other'
]

// Soil Types - from old app sourceSelectSoil
export const SOIL_TYPES = [
  'Bentonite',
  'Other'
]

// Igneous Rock Types - from old app sourceSelectIgneous
export const IGNEOUS_ROCK_TYPES = [
  'alkali feldspar granite',
  'andesite',
  'anorthosite',
  'aplite',
  'basalt',
  'diabase',
  'diorite',
  'dunite',
  'gabbro',
  'granite',
  'granodiorite',
  'harzburgite',
  'kimberlite',
  'komatiite',
  'lamprophyre',
  'lapilli tuff',
  'lherzolite',
  'monzonite',
  'norite',
  'obsidian',
  'pegmatite',
  'peridotite',
  'phonolite',
  'pumice',
  'pyroxenite',
  'quartz monzonite',
  'rhyolite',
  'scoria',
  'syenite',
  'tonalite',
  'trachyandesite',
  'trachyte',
  'troctolite',
  'tuff',
  'tuff breccia',
  'wehrlite',
  'Other'
]

// Sedimentary Rock Types - from old app sourceSelectSedimentary
export const SEDIMENTARY_ROCK_TYPES = [
  'argillite',
  'arkose',
  'breccia',
  'chalk',
  'chert',
  'claystone',
  'coal',
  'conglomerate',
  'coquina',
  'diatomite',
  'dolomite',
  'dolostone',
  'evaporite',
  'flint',
  'graywacke',
  'gypsum rock',
  'ironite formation',
  'ite',
  'limestone',
  'marl',
  'mudstone',
  'oil shale',
  'organic',
  'phosphatic',
  'rock salt',
  'sandstone',
  'shale',
  'siltstone',
  'travertine',
  'volcaniclastic',
  'wackestone',
  'Other'
]

// Metamorphic Rock Types - from old app sourceSelectMetamorphic
export const METAMORPHIC_ROCK_TYPES = [
  'amphibolite',
  'anthracite',
  'blackwall',
  'blueschist',
  'cataclasite',
  'eclogite',
  'garnetite',
  'glaucophanite',
  'gneiss',
  'granofels',
  'granulite',
  'greenschist',
  'greenstone',
  'hornfels',
  'marble',
  'meta-iron formation',
  'meta-ultramafic',
  'metaarkose',
  'metabasite',
  'metacarbonate',
  'metagranite',
  'metagraywacke',
  'metaigneous',
  'metapelite',
  'metasandstone',
  'migmatite',
  'mylonite',
  'orthogneiss',
  'paragneiss',
  'phyllite',
  'phyllonite',
  'pseudotachylyte',
  'pyroxenite',
  'quartzite',
  'rodingite',
  'schist',
  'serpentinite',
  'skarn',
  'slate',
  'soapstone',
  'whiteschist',
  'Other'
]

// Epos Lithology Types - from old app sourceSelectEpos (extensive list)
export const EPOS_LITHOLOGY_TYPES = [
  'acidic_igneous_material',
  'acidic_igneous_rock',
  'alkali - olivine_basalt',
  'alkali_feldspar_granite',
  'alkali_feldspar_rhyolite',
  'alkali_feldspar_syenite',
  'alkali_feldspar_syenitic_rock',
  'alkali_feldspar_trachyte',
  'alkali_feldspar_trachytic_rock',
  'amphibolite',
  'andesite',
  'anorthosite',
  'anorthositic_rock',
  'anthracite_coal',
  'anthropogenic_material',
  'anthropogenic_unconsolidated_material',
  'aphanite',
  'aplite',
  'arenite',
  'ash_and_lapilli',
  'ash_breccia_bomb_or_block_tephra',
  'ash_tuff_lapillistone_and_lapilli_tuff',
  'basalt',
  'basanite',
  'basanitic_foidite',
  'basic_igneous_material',
  'basic_igneous_rock',
  'bauxite',
  'biogenic_sediment',
  'biogenic_silica_sedimentary_rock',
  'bituminous_coal',
  'boninite',
  'boulder_gravel_size_sediment',
  'boundstone',
  'breccia',
  'breccia_gouge_series',
  'calcareous_carbonate_sedimentary_material',
  'calcareous_carbonate_sedimentary_rock',
  'calcarite_carbonate_sediment',
  'calcite calciumite calcium calcium calcium calcium_calcium',
  'calcium car',
  'calcium te',
  'calcium te calcium te',
  'calcium te calcium te calcium te',
  'calcium te calcium te calcium te calcium te',
  'calcium te calcium te calcium te calcium te calcium te',
  'calciumite',
  'calclite',
  'car bonite',
  'carbonate_mud',
  'carbonate_mudstone',
  'carbonate_ooze',
  'carbonate_rich_mud',
  'carbonate_rich_mudstone',
  'carbonate_sediment',
  'carbonate_sedimentary_material',
  'carbonate_sedimentary_rock',
  'carbonate_wackestone',
  'carbonite',
  'cataclasite_series',
  'chalk',
  'chemical_sedimentary_material',
  'chlorite_actinolite_epidote_metamorphic_rock',
  'clastic_conglomerate',
  'clastic_mudstone',
  'clastic_sandstone',
  'clastic_sediment',
  'clastic_sedimentary_material',
  'clastic_sedimentary_rock',
  'clay',
  'claystone',
  'coal',
  'cobble_gravel_size_sediment',
  'composite_genesis_material',
  'composite_genesis_rock',
  'compound_material',
  'crystalline_carbonate',
  'dacite',
  'diamictite',
  'diamicton',
  'diorite',
  'dioritic_rock',
  'dioritoid',
  'doleritic_rock',
  'doloite',
  'dolomitic_or_magnesian_sedimentary_material',
  'dolomitic_or_magnesian_sedimentary_rock',
  'dolomitic_sediment',
  'dolostone',
  'duricrust',
  'eclogite',
  'evaporite',
  'exotic_alkaline_rock',
  'exotic_composition_igneous_rock',
  'exotic_evaporite',
  'fault_related_material',
  'fine_grained_igneous_rock',
  'foid_bearing_alkali_feldspar_syenite',
  'foid_bearing_alkali_feldspar_trachyte',
  'foid_bearing_anorthosite',
  'foid_bearing_diorite',
  'foid_bearing_gabbro',
  'foid_bearing_latite',
  'foid_bearing_monzodiorite',
  'foid_bearing_monzogabbro',
  'foid_bearing_monzonite',
  'foid_bearing_syenite',
  'foid_bearing_trachyte',
  'foid_diorite',
  'foid_dioritoid',
  'foid_gabbro',
  'foid_gabbroid',
  'foid_monzodiorite',
  'foid_monzogabbro',
  'foid_monzosyenite',
  'foid_syenite',
  'foid_syenitoid',
  'foidite',
  'foiditoid',
  'foidolite',
  'foliated_metamorphic_rock',
  'fragmental_igneous_material',
  'fragmental_igneous_rock',
  'framestone',
  'gabbro',
  'gabbroic_rock',
  'gabbroid',
  'generic_conglomerate',
  'generic_mudstone',
  'generic_sandstone',
  'glass_rich_igneous_rock',
  'glassy_igneous_rock',
  'glaucophane_lawsonite_epidote_metamorphic_rock',
  'gneiss',
  'grainstone',
  'granite',
  'granitoid',
  'granodiorite',
  'granofels',
  'granulite',
  'gravel',
  'gravel_size_sediment',
  'high_magnesium_fine_grained_igneous_rocks',
  'hornblendite',
  'hornfels',
  'hybrid_sediment',
  'hybrid_sedimentary_rock',
  'igneous_material',
  'igneous_rock',
  'impact_generated_material',
  'impure_calcarite_carbonate_sediment',
  'impure_carbonate_sediment',
  'impure_carbonate_sedimentary_rock',
  'impure_dolomitic_sediment',
  'impure_dolostone',
  'impure_limestone',
  'intermediate_composition_igneous_material',
  'intermediate_composition_igneous_rock',
  'iron_rich_sediment',
  'iron_rich_sedimentary_material',
  'iron_rich_sedimentary_rock',
  'ite',
  'kalsilitic_and_melilitic_rock',
  'komatiitic_rock',
  'latite',
  'latitic_rock',
  'lignite',
  'limestone',
  'marble',
  'material_formed_in_surficial_environment',
  'metamorphic_rock',
  'metasomatic_rock',
  'mica_schist',
  'migmatite',
  'monzodiorite',
  'monzodioritic_rock',
  'monzogabbro',
  'monzogabbroic_rock',
  'monzogranite',
  'monzonite',
  'monzonitic_rock',
  'mud',
  'mud_size_sediment',
  'mylonitic_rock',
  'natural_unconsolidated_material',
  'non_clastic_siliceous_sediment',
  'non_clastic_siliceous_sedimentary_material',
  'non_clastic_siliceous_sedimentary_rock',
  'ooze',
  'organic_bearing_mudstone',
  'organic_rich_sediment',
  'organic_rich_sedimentary_material',
  'organic_rich_sedimentary_rock',
  'orthogneiss',
  'packstone',
  'paragneiss',
  'peat',
  'pegmatite',
  'peridotite',
  'phaneritic_igneous_rock',
  'phonolite',
  'phonolitic_basanite',
  'phonolitic_foidite',
  'phonolitic_tephrite',
  'phonolitoid',
  'phosphate_rich_sediment',
  'phosphate_rich_sedimentary_material',
  'phosphorite',
  'phyllite',
  'phyllonite',
  'porphyry',
  'pure_calcarite_carbonate_sediment',
  'pure_carbonate_mudstone',
  'pure_carbonate_sediment',
  'pure_carbonate_sedimentary_rock',
  'pure_dolomitic_sediment',
  'pyroclastic_material',
  'pyroclastic_rock',
  'pyroxenite',
  'quartz_alkali_feldspar_syenite',
  'quartz_alkali_feldspar_trachyte',
  'quartz_anorthosite',
  'quartz_diorite',
  'quartz_gabbro',
  'quartz_latite',
  'quartz_monzodiorite',
  'quartz_monzogabbro',
  'quartz_monzonite',
  'quartz_rich_igneous_rock',
  'quartz_syenite',
  'quartz_trachyte',
  'quartzite',
  'residual_material',
  'rhyolite',
  'rhyolitoid',
  'rock',
  'rock_gypsum_or_anhydrite',
  'rock_salt',
  'sand',
  'sand_size_sediment',
  'sapropel',
  'schist',
  'sediment',
  'sedimentary_material',
  'sedimentary_rock',
  'serpentinite',
  'shale',
  'silicate_mud',
  'silicate_mudstone',
  'siliceous_ite',
  'silt',
  'siltstone',
  'skarn',
  'slate',
  'spilite',
  'syenite',
  'syenitic_rock',
  'syenitoid',
  'syenogranite',
  'tephra',
  'tephrite',
  'tephritic_foidite',
  'tephritic_phonolite',
  'tephritoid',
  'tholeiitic_basalt',
  'tonalite',
  'trachyte',
  'trachytic_rock',
  'trachytoid',
  'travertine',
  'tuff_breccia_agglomerate_or_pyroclastic_breccia',
  'tuffite',
  'ultrabasic_igneous_rock',
  'ultramafic_igneous_rock',
  'unconsolidated_material',
  'wacke',
  'Other'
]

// Lab Standards - from old app sourceSelectStandards
export const LAB_STANDARDS = [
  'Arkansas Novaculite',
  'Austin Chalk',
  'Berea Sandstone',
  'Black Hills Quartzite',
  'Carrara Marble',
  'Cheshire Quartzite',
  'Frederick Maryland Diabase',
  'Heavitree Quartzite',
  'Indiana Limestone',
  'Simpson Quartzite',
  'Sioux Quartzite',
  'Solnhofen Limestone',
  'Westerley Granite',
  'Other'
]

// Commodity Types - from old app sourceSelectCommodity (extensive list)
export const COMMODITY_TYPES = [
  'agate',
  'aggregate',
  'alumina',
  'aluminium',
  'aluminosilicate',
  'alunite',
  'amazonite',
  'amber',
  'amethyst',
  'andalusite',
  'anhydrite',
  'anthophyllite',
  'anthracite',
  'antimony',
  'apatite',
  'apatite - gemstone',
  'aquamarine',
  'arsenic',
  'asbestos',
  'asbestos - amphibole',
  'asbestos - serpentine',
  'asphalt',
  'barium',
  'baryte',
  'basalt',
  'base - metal',
  'bauxite',
  'bentonite',
  'beryl',
  'beryllium',
  'bismuth',
  'black - coal',
  'borate',
  'boron',
  'brick - clay',
  'bromine',
  'brown - coal',
  'cadmium',
  'calcite',
  'carbonaceous - material',
  'carnallite',
  'carnelian',
  'cassiterite - gemstone',
  'cerium',
  'cesium',
  'chalcedony',
  'chemical - compound - product',
  'chemical - oxide - product',
  'chert',
  'chlorite',
  'chrome',
  'chromite',
  'chromium',
  'chrysoberyl',
  'chrysoprase',
  'chrysotile',
  'citrine',
  'clay',
  'coal',
  'coal - bed - methane',
  'cobalt',
  'copper',
  'corundum',
  'corundum - gemstone',
  'crocidolite',
  'crushed - rock',
  'cryolite',
  'diamond',
  'diamond - gemstone',
  'diatomite',
  'dimension - stone',
  'diopside - enstatite',
  'dioptase',
  'direct - shipping - ore',
  'direct - use - commodity',
  'dumortierite',
  'dysprosium',
  'emerald',
  'epsomite',
  'erbium',
  'euclase',
  'europium',
  'evaporite',
  'feldspar',
  'feldspar - gemstone',
  'ferrous - metal',
  'fluorine',
  'fluorite',
  'foundry - sand',
  'frac - sand',
  'fullers - earth',
  'gadolinium',
  'gallium',
  'garnet',
  'garnet - gemstone',
  'gas - hydrate',
  'gaseous - hydrocarbons',
  'gemstones',
  'germanium',
  'glauconite',
  'gold',
  'granite',
  'graphite',
  'greenstone',
  'gypsum',
  'hafnium',
  'halloysite',
  'heavy - rare - earth - oxide',
  'heliodor',
  'hematite',
  'hematite - gemstone',
  'hematite - ore',
  'holmium',
  'hree',
  'ilmenite',
  'indium',
  'industrial - material',
  'industrial - mineral',
  'industrial - rock',
  'iodine',
  'iolite',
  'iridium',
  'iron',
  'iron - ore',
  'iron - oxide',
  'jade',
  'jarosite',
  'kaolin',
  'kornerupine',
  'kyanite',
  'kyanite - gemstone',
  'lanthanum',
  'laterite',
  'lazulite',
  'lead',
  'leucoxene',
  'light - rare - earth - oxide',
  'lime',
  'limestone',
  'liquid - hydrocarbons',
  'lithium',
  'lithium - oxide',
  'lree',
  'lutetium',
  'magnesia',
  'magnesite',
  'magnesium',
  'magnetite',
  'magnetite - ore',
  'malachite',
  'manganese',
  'manganese - ore',
  'marble',
  'mercury',
  'metal',
  'metalloid',
  'mica',
  'miscellaneous - dimension - stones',
  'molybdenite',
  'molybdenum',
  'monazite',
  'moonstone',
  'morganite',
  'moss - agate',
  'natural - secondary - aggregate',
  'neodymium',
  'nepheline - syenite',
  'nickel',
  'niobium',
  'niobium - pentoxide',
  'nitrate',
  'non - metal',
  'obsidian',
  'ochre',
  'oil',
  'oil - shale',
  'olivine',
  'olivine - gemstone',
  'onyx',
  'opal',
  'organic - material',
  'osmium',
  'palladium',
  'palygorskite',
  'peat',
  'perlite',
  'phenakite',
  'phosphate - rock',
  'phosphorous',
  'phosphorous - pentoxide',
  'platinum',
  'platinum - group',
  'potash',
  'potassium',
  'pozzolan',
  'praseodymium',
  'precious - metal',
  'prehnite',
  'primary - aggregate',
  'produced - commodity',
  'promethium',
  'pumice',
  'pyrite',
  'pyrophyllite',
  'quartz',
  'quartz - gemstone',
  'radium',
  'rare - earth - element',
  'rare - earth - oxide',
  'recycled - aggregate',
  'reservoir - gas',
  'rhenium',
  'rhodium',
  'rhodonite',
  'riprap',
  'rose - quartz',
  'rubidium',
  'ruby',
  'ruthenium',
  'rutile',
  'salt',
  'samarium',
  'sand',
  'sand - and - gravel',
  'sandstone',
  'saponite',
  'sapphire',
  'sapphirine',
  'scandium',
  'scapolite',
  'selenium',
  'sepiolite',
  'sericite',
  'serpentine',
  'shell - grit',
  'silica',
  'silica - gemstone',
  'silicon',
  'sillimanite',
  'silver',
  'sinhalite',
  'slate',
  'smokey - quartz',
  'soda - ash',
  'sodalite',
  'spectrolite',
  'spinel',
  'spinel - gemstone',
  'spodumene',
  'spongolite',
  'staurolite',
  'strontianite',
  'strontium',
  'sulphur',
  'sylvite',
  'talc',
  'tantalum',
  'tantalum - pentoxide',
  'tanzanite',
  'tar - sand',
  'tellurium',
  'terbium',
  'thallium',
  'thenardite',
  'thorium',
  'thulium',
  'tin',
  'titanium',
  'topaz',
  'tourmaline',
  'tremolite - actinolite',
  'tsavorite',
  'tungsten',
  'turquoise',
  'uranium',
  'uranium - oxide',
  'vanadium',
  'vanadium - pentoxide',
  'variscite',
  'vermiculite',
  'vesuvianite',
  'white - firing - clay',
  'wollastonite',
  'xenotime - gemstone',
  'ytterbium',
  'yttrium',
  'yttrium - oxide',
  'zeolite',
  'zinc',
  'zircon',
  'zircon - gemstone',
  'zirconia',
  'zirconium',
  'Other'
]

// Material types that use text input for name (instead of dropdown)
export const TEXT_INPUT_MATERIAL_TYPES = [
  'Ceramic',
  'Glass',
  'Ice',
  'Metal',
  'Plastic'
]

// Mapping of material type to label for the name field
export const MATERIAL_NAME_LABELS = {
  'Glass': 'Name',
  'Ice': 'Name',
  'Ceramic': 'Name',
  'Plastic': 'Name',
  'Metal': 'Name',
  'Soil': 'Soil Type',
  'Mineral': 'Mineral Name',
  'Igneous Rock': 'Igneous Rock',
  'Sedimentary Rock': 'Sedimentary Rock',
  'Metamorphic Rock': 'Metamorphic Rock',
  'Epos Lithologies': 'Epos Lithology',
  'Standards': 'Lab Standard',
  'Commodity': 'Commodity Name'
}

// Mapping of material type to dropdown options
export const MATERIAL_NAME_OPTIONS = {
  'Soil': SOIL_TYPES,
  'Mineral': MINERAL_TYPES,
  'Igneous Rock': IGNEOUS_ROCK_TYPES,
  'Sedimentary Rock': SEDIMENTARY_ROCK_TYPES,
  'Metamorphic Rock': METAMORPHIC_ROCK_TYPES,
  'Epos Lithologies': EPOS_LITHOLOGY_TYPES,
  'Standards': LAB_STANDARDS,
  'Commodity': COMMODITY_TYPES
}

// ===== EXPERIMENTAL SETUP ENUMS =====

// Geometry component types
export const GEOMETRY_COMPONENT_TYPES = [
  'Forcing Block',
  'Jacket',
  'Sample',
  'Spacer'
]

// Geometry shape options
export const GEOMETRY_SHAPES = [
  'Circular',
  'Cylinder',
  'Dogbone',
  'Precut',
  'Rectangular',
  'Split Cylinder',
  'Tube'
]

// Geometry material options
export const GEOMETRY_MATERIALS = [
  'Alumina',
  'Copper',
  'Gold',
  'Iron',
  'Nickel',
  'PET',
  'Platinum',
  'Porous Alumina',
  'PTFE',
  'PVC',
  'PZT',
  'Rubber',
  'Sample',
  'Silver',
  'Viton',
  'Zirconia'
]

// Dimension variable options
export const DIMENSION_VARIABLES = [
  'Bore Diameter',
  'Diameter',
  'Fault Angle',
  'Height',
  'Length',
  'Span',
  'Wall Thickness',
  'Width'
]

// ===== DAQ (Data Acquisition) ENUMS =====

// DAQ system types - from old app
export const DAQ_TYPES = [
  'Conventional',
  'Proprietary',
  'Standard'
]

// Channel Header Types - from old app lines 1084-1094
export const CHANNEL_HEADER_TYPES = [
  'Chemistry',
  'Displacement',
  'Electrical',
  'Load',
  'Pressure',
  'Strain',
  'Stress',
  'Temperature',
  'Time',
  'Other'
]

// Channel types (signal types) - from old app lines 1197-1206
export const CHANNEL_TYPES = [
  'Analog Input',
  'Analog Output',
  'Calculated',
  'Digital Input',
  'Digital Output',
  'System Clock',
  'System Data'
]

// Channel electrical configurations - from old app lines 1212-1222
export const CHANNEL_CONFIGURATIONS = [
  'Differential',
  'Line',
  'Parallel',
  'Referenced Single Ended',
  'Serial',
  'Single',
  'Single Ended',
  'System'
]

// Channel gain (amplification) options - from old app lines 1266-1276
export const CHANNEL_GAINS = [
  'x1',
  'x2',
  'x5',
  'x10',
  'x20',
  'x25',
  'x50',
  'x100'
]

// Channel numbers (0-32)
export const CHANNEL_NUMBERS = Array.from({ length: 33 }, (_, i) => String(i))

// Sensor/Actuator types - from old app lines 1291-1317
export const SENSOR_ACTUATOR_TYPES = [
  '--',
  'Actuator',
  'Capacitive Load Cell',
  'Clock',
  'DCDT',
  'Encoder',
  'Flow Meter',
  'Force Gauge',
  'Hall Sensor',
  'Heater',
  'Linear Motor',
  'Load Cell',
  'LVDT',
  'P-Wave Sensor',
  'pH-Meter',
  'Power',
  'Pressure Transducer',
  'S-Wave Sensor',
  'Servo Motor',
  'Step Motor',
  'Strain Gauge',
  'Thermistor',
  'Thermocouple',
  'Trigger'
]

// Sensor active/passive types - from old app lines 1349-1353
export const SENSOR_ACTIVE_PASSIVE_TYPES = [
  'Active',
  'Passive'
]

// IEEE Sensor Templates - from old app lines 1323-1341
export const IEEE_SENSOR_TEMPLATES = [
  'Accelerometer & Force',
  'Bridge Sensors',
  'Charge Amplifier (w/ attached accelerometer)',
  'Charge Amplifier (w/ attached force transducer)',
  'Current Loop Output Sensors',
  'High-Level Voltage Output Sensors',
  'LVDT/RVDT Sensors',
  'Microphone Preamplfiers (w/ attached microphone)',
  'Microphone with built-in preamplifier',
  'Microphones (capacitive)',
  'Potentiometric Voltage Divider',
  'Resistance Sensors',
  'Resistance Temperature Detectors (RTDs)',
  'Strain Gage',
  'Thermistor',
  'Thermocouple'
]

// Calibration Templates - from old app lines 1404-1411
export const CALIBRATION_TEMPLATES = [
  '(a0:a1)(a2:a3)',
  'Base:Exponent',
  'Frequency:Amplitude',
  'Input:Unit',
  'Input@0:Input/Unit'
]

// ===== DAQ CHANNEL HEADER DATA FIELDS =====
// From /experimental/experimental_data_fields.js
// This array drives the dynamic dropdown population for spec_a, spec_b, and unit
// based on the selected header type
export const DAQ_DATA_FIELDS = [
  // Time
  { headerType: 'Time', fieldVal: 'spec_a', selectVal: 'Absolute' },
  { headerType: 'Time', fieldVal: 'spec_a', selectVal: 'Relative' },
  { headerType: 'Time', fieldVal: 'spec_b', selectVal: 'Total' },
  { headerType: 'Time', fieldVal: 'spec_b', selectVal: 'Differential' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'sec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'min' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'hour' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'day' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'ysec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'msec' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'UTC' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'dd-mm-yyyy' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'mm/dd/yy' },
  { headerType: 'Time', fieldVal: 'unit', selectVal: 'hh-mm-ss' },
  // Temperature
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Room' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Sample' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Furnace' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Fluid' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Pore' },
  { headerType: 'Temperature', fieldVal: 'spec_a', selectVal: 'Vessel' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Top' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Bottom' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Temperature', fieldVal: 'spec_b', selectVal: 'Average' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg C' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg K' },
  { headerType: 'Temperature', fieldVal: 'unit', selectVal: 'deg F' },
  // Pressure
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Barometric' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Pore' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Effective' },
  { headerType: 'Pressure', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Vessel' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Intensifier' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Upstream' },
  { headerType: 'Pressure', fieldVal: 'spec_b', selectVal: 'Downstream' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'bar' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'kPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'MPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'GPa' },
  { headerType: 'Pressure', fieldVal: 'unit', selectVal: 'PSI' },
  // Strain
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Total' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'Volumetric' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Strain', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Strain', fieldVal: 'spec_b', selectVal: 'Rate' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: 'mStrain' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: 'Strain' },
  { headerType: 'Strain', fieldVal: 'unit', selectVal: '1/sec' },
  // Displacement
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Total' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'Volumetric' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Displacement', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Rate' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Pore Pressure Intensifier' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Confining Pressure Intensifier' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Pore Volume' },
  { headerType: 'Displacement', fieldVal: 'spec_b', selectVal: 'Confining Volume' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: '%' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'μm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'mm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'm' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'mm/s' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'inches' },
  { headerType: 'Displacement', fieldVal: 'unit', selectVal: 'feet' },
  // Stress
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Normal' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Stress', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Stress', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'Pa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'KPa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'MPa' },
  { headerType: 'Stress', fieldVal: 'unit', selectVal: 'GPa' },
  // Load
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Axial' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Radial' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Shear' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Normal' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Differential' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Average' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ1' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ2' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'σ3' },
  { headerType: 'Load', fieldVal: 'spec_a', selectVal: 'Confining' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'Internal' },
  { headerType: 'Load', fieldVal: 'spec_b', selectVal: 'External' },
  { headerType: 'Load', fieldVal: 'unit', selectVal: 'N' },
  { headerType: 'Load', fieldVal: 'unit', selectVal: 'KN' },
  // Electrical
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Conductivity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Resistivity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Capacity' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Spontaneous Potential' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'AC Voltage' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'DC Voltage' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Current' },
  { headerType: 'Electrical', fieldVal: 'spec_a', selectVal: 'Induction' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Sample' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Pore Fluid' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Total' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Heating' },
  { headerType: 'Electrical', fieldVal: 'spec_b', selectVal: 'Cooling' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'μVolt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'mVolt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Volt' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'A' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'mA' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'S' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'S/m' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'F' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Ω' },
  { headerType: 'Electrical', fieldVal: 'unit', selectVal: 'Ωm' },
  // Chemistry
  { headerType: 'Chemistry', fieldVal: 'spec_a', selectVal: 'Pore Fluid' },
  { headerType: 'Chemistry', fieldVal: 'spec_a', selectVal: 'Fluid' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'pH' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'pOH' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Na+' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'K+' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Ca++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Mg++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'Sr++' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'HCO3-' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'TOC' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'TIC' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'CO2(gas)' },
  { headerType: 'Chemistry', fieldVal: 'spec_b', selectVal: 'CO2(sol)' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'mol/L' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'mMol/L' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'ppm' },
  { headerType: 'Chemistry', fieldVal: 'unit', selectVal: 'cc' },
  // Other - extensive list of spec_a values (no spec_b)
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Acoustic Emissions' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Acoustic Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Amplitude' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Anisotropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Area' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Attenuation' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Bulk Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Capacitance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Centrifugal Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Chemical Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Coldness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Confining Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Current Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Downstream Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Dynamic Viscosity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Elasticity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Elastic Wave Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric charge' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric Charge Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electric Current' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Resistance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Electrical Resistivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Fracture Toughness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Frequency' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Friction Coefficient' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Heat' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Hydraulic Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Impedance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Impulse' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Inductance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Intensity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Irradiance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Lame Parameter' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Length' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Linear Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Luminance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Field Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Flux' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Mass Fraction' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Concentration' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Molar Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Moment of Force' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Moment of Inertia' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Momentum' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Magnetic Permittivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Permeability' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Plane Angle' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: "Poisson's Ratio" },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'P-Wave Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Radiance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Radioactive Dose' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Reaction Rate' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Refractive Index' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Roughness' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Shear Modulus' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Solid Angle' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Energy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Entropy' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Heat Capacity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Specific Volume' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Spontaneous Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Strain' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Streaming Potential' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Stress' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Charge Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Density' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Surface Tension' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Temperature' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Temperature Gradient' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Conductance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Conductivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Resistance' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Thermal Resistivity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Time' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Torque' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Upstream Pore Pressure' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Velocity' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Volume' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Volumetric Flow Rate' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavelength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavenumber' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Wavevector' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Weight' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Work' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: 'Yield Strength' },
  { headerType: 'Other', fieldVal: 'spec_a', selectVal: "Young's Modulus" }
]

// Helper function to get options for a specific header type and field
export function getDAQOptionsForHeader(headerType, fieldType) {
  if (!headerType) return []

  const options = DAQ_DATA_FIELDS
    .filter(df => df.headerType === headerType && df.fieldVal === fieldType)
    .map(df => df.selectVal)

  // Return unique values
  return [...new Set(options)]
}

// Contact affiliation roles
export const CONTACT_AFFILIATIONS = [
  'Co-PI',
  'Director',
  'Engineer',
  'Manager',
  'PI',
  'Postdoc',
  'Scientist',
  'Student',
  'Technician',
  'Other'
]

// ===== DATA FORM ENUMS =====
// From old app add_experiment.php lines 3826-3862

// Data source types (the main "Data" dropdown)
export const DATA_SOURCE_TYPES = [
  'Acid Etching',
  'CL',
  'Confocal Microscopy',
  'CT Scan',
  'EBSD',
  'EDS',
  'EDX',
  'Evaporative Grid',
  'Fiducal Marks',
  'Fluorescence',
  'Imaging',
  'Infrared',
  'Infrared Spectroscopy',
  'Neutron Diffraction',
  'Optical Microscopy',
  'Parameters',
  'Photoelasticity',
  'Polarized Microscopy',
  'Pore Fluid',
  'Profilometry',
  'Raman',
  'Raman',
  'Sample Description',
  'SEM',
  'TEM',
  'Thermal Etching',
  'Thin Section',
  'Time Series',
  'WDS',
  'X-Ray Graphs',
  'X-Ray Spectra',
  'XRCT',
  'XRD',
  'XRF'
]

// Data type options (Picture, Video, etc.)
export const DATA_TYPE_OPTIONS = [
  'Data',
  'Picture',
  'Software',
  'Video',
  'Other'
]

// File format options
export const DATA_FILE_FORMATS = [
  'csv',
  'rar',
  'text',
  'zip',
  'Other'
]

// Data quality rating
export const DATA_QUALITY_RATINGS = [
  'Low',
  'Acceptable',
  'Good',
  'Very Good',
  'Exceptional'
]

// Data parameter control variables - from old app lines 3994-4029
export const DATA_PARAMETER_CONTROLS = [
  'Bore Diameter',
  'Compressive Strength (σ1=σ2)',
  'Compressive Strength (σ2=σ3)',
  'Connected Porosity',
  'Corrected Strain Rate ε/dt',
  'Density',
  'Diameter',
  'Fault Angle',
  'Final Displacement Δs',
  'Final Strain ε',
  'Flow Strength',
  'Fluid Permeability',
  'Fracture Strength',
  'Friction Parameter',
  'Gas Permeability',
  'Height',
  'Length',
  'Machine Stiffness N/mm',
  'Maximum Force F',
  'Maximum Stress σ',
  'Roughness',
  'Span',
  'Tensional Strength',
  'Torsion Strength',
  'Total Porosity',
  'True Tension Strength',
  'True Triaxial Strength',
  'Ultimate Shear Strength',
  'Ultimate Tensile Strength',
  'Unconfined Compressive Strength (UCS)',
  'Unconnected Porosity',
  'Weight',
  'Width',
  'Yield Strength',
  'Yield Stress σ'
]

// Data header channel types - from old app lines 4365-4372
export const DATA_HEADER_CHANNEL_TYPES = [
  'Analog Input',
  'Analog Output',
  'Calculated',
  'Digital Input',
  'Digital Output',
  'System Clock',
  'System Data'
]

// Pore fluid phase unit options - from old app lines 4171-4174
export const PHASE_UNIT_OPTIONS = [
  'Mol%',
  'MPa',
  'Vol%',
  'Wt%'
]

// Pore fluid chemistry data options - from old app lines 4182-4183
export const CHEMISTRY_DATA_OPTIONS = [
  'Chemistry',
  'None'
]

// Solute component options - from old app lines 4233-4246
// Note: "Resitivity" is a typo in the old app, kept for compatibility
export const SOLUTE_COMPONENTS = [
  'Ca++',
  'CO2(gas)',
  'CO2(sol)',
  'HCO3-',
  'K+',
  'Mg++',
  'Na+',
  'pH',
  'pOH',
  'Resitivity',
  'Sr++',
  'Temperature',
  'TIC',
  'TOC'
]

// Solute unit options - from old app lines 4257-4264
export const SOLUTE_UNITS = [
  'deg C',
  'log [C]',
  'mMol/L',
  'Mol/L',
  'Mol%',
  'S/Mol',
  'Vol%',
  'Wt%'
]

// ===== PROTOCOL ENUMS =====

// Protocol control variables - from old app edit_experiment.php lines 3493-3517
// These are the parameter variables for protocol steps
export const PROTOCOL_CONTROL_VARIABLES = [
  'Amplitude',
  'Confining Pressure Pc',
  'Count',
  'Displacement Δs1',
  'Displacement Δs2',
  'Displacement Δs3',
  'Force F2',
  'Force F2',
  'Force F3',
  'Frequency',
  'Humidity',
  'Pore Pressure Pp',
  'Saturation',
  'Strain Rate ε1/dt',
  'Strain Rate ε2/dt',
  'Strain Rate ε3/dt',
  'Strain ε1',
  'Strain ε2',
  'Strain ε3',
  'Stress σ1',
  'Stress σ2',
  'Stress σ3',
  'Temperature T',
  'Time t'
]

// ===== VARIABLE-TO-UNIT MAPPING =====
// Maps physical quantity categories to applicable UNIT_TYPES values
// Used to filter the unit dropdown based on the selected variable/parameter

const UNIT_CATEGORIES = {
  temperature: ['degC', 'degK'],
  time: ['sec', 'min', 'hour'],
  electrical: ['Volt', 'mV', 'Amperage', 'mA', 'Ohm'],
  pressure: ['Pa', 'MPa', 'GPa', 'bar', 'kbar'],
  force: ['N', 'kN'],
  mass: ['g', 'mg', 'μg'],
  length: ['m', 'cm', 'mm', 'μm'],
  frequency: ['Hz', 'kHz', 'MHz'],
  viscosity: ['Pa·s'],
  permeability: ['Darcy', 'mDarcy'],
  strain: ['milistrain', '%'],
  rate: ['mm·sec-1', 'N·sec-1', 'sec-1'],
  stiffness: ['kN·mm-1'],
  percentage: ['%'],
  count: ['count'],
  volume: ['cc', 'mm3'],
  area: ['m2'],
  inverseLength: ['m-1']
}

// Maps variable/parameter names to their applicable unit categories
// Variables not listed here fall back to the full UNIT_TYPES list
const VARIABLE_TO_CATEGORIES = {
  // PARAMETER_TYPES (Apparatus)
  'Confining Pressure': ['pressure'],
  'Effective Pressure': ['pressure'],
  'Pore Pressure': ['pressure'],
  'σ1-Displacement': ['length'],
  'σ2-Displacement': ['length'],
  'σ3-Displacement': ['length'],
  'σ1-Load': ['force'],
  'σ2-Load': ['force'],
  'σ3-Load': ['force'],
  'Displacement Rate': ['rate'],
  'Loading Rate': ['rate'],
  'Stiffness': ['stiffness'],
  'Sample Diameter': ['length'],
  'Sample Length': ['length'],
  'Permeability': ['permeability'],

  // SAMPLE_PARAMETER_TYPES
  'Weight': ['mass'],
  'Connected Porosity': ['percentage'],
  'Unconnected Porosity': ['percentage'],
  'Total Porosity': ['percentage'],
  // Note: Density (mass/volume) has no matching compound unit in UNIT_TYPES, so it falls back to the full list
  'Permeability (Gas)': ['permeability'],
  'Permeability (Water)': ['permeability'],
  'Temperature': ['temperature'],
  'Humidity': ['percentage'],
  'Fluid Saturation': ['percentage'],
  'Stress': ['pressure'],

  // DIMENSION_VARIABLES
  'Length': ['length'],
  'Diameter': ['length'],
  'Width': ['length'],
  'Span': ['length'],
  'Height': ['length'],
  'Wall Thickness': ['length'],
  'Bore Diameter': ['length'],

  // PROTOCOL_CONTROL_VARIABLES
  'Time t': ['time'],
  'Stress σ1': ['pressure'],
  'Strain ε1': ['strain'],
  'Strain Rate ε1/dt': ['rate'],
  'Displacement Δs1': ['length'],
  'Force F2': ['force'],
  'Stress σ2': ['pressure'],
  'Strain ε2': ['strain'],
  'Strain Rate ε2/dt': ['rate'],
  'Displacement Δs2': ['length'],
  'Stress σ3': ['pressure'],
  'Strain ε3': ['strain'],
  'Strain Rate ε3/dt': ['rate'],
  'Displacement Δs3': ['length'],
  'Force F3': ['force'],
  'Saturation': ['percentage'],
  'Count': ['count'],

  // DATA_PARAMETER_CONTROLS
  'Gas Permeability': ['permeability'],
  'Fluid Permeability': ['permeability'],
  'Final Strain ε': ['strain'],
  'Corrected Strain Rate ε/dt': ['rate'],
  'Final Displacement Δs': ['length'],
  'Maximum Force F': ['force'],
  'Maximum Stress σ': ['pressure'],
  'Yield Stress σ': ['pressure'],
  'Machine Stiffness N/mm': ['stiffness'],
  'Roughness': ['length'],
  'Friction Parameter': ['percentage', 'count'],
  'Unconfined Compressive Strength (UCS)': ['pressure'],
  'Ultimate Tensile Strength': ['pressure'],
  'Ultimate Shear Strength': ['pressure'],
  'True Tension Strength': ['pressure'],
  'Compressive Strength (σ2=σ3)': ['pressure'],
  'Compressive Strength (σ1=σ2)': ['pressure'],
  'True Triaxial Strength': ['pressure'],
  'Yield Strength': ['pressure'],
  'Tensional Strength': ['pressure'],
  'Torsion Strength': ['pressure'],
  'Flow Strength': ['pressure'],
  'Fracture Strength': ['pressure']
}

// Returns the applicable unit options for a given variable/parameter name.
// Falls back to the full UNIT_TYPES list for unknown variables (e.g., "Other", "Fault Angle").
export function getUnitsForVariable(variableName) {
  if (!variableName) return UNIT_TYPES

  const categories = VARIABLE_TO_CATEGORIES[variableName]
  if (!categories) return UNIT_TYPES

  const units = []
  for (const cat of categories) {
    const catUnits = UNIT_CATEGORIES[cat]
    if (catUnits) units.push(...catUnits)
  }
  return [...new Set(units)]
}
